### ISSUE TITLE
Git for Windows' Bash is not recognized as an interactive session

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1014]
### Describe the bug

Running `./batect` (the shell script) from "Git Bash" (which uses [mintty](https://mintty.github.io/)) that ships with Git for Windows results in the hint:

```
It looks like Batect is running in a non-interactive session, so it can't ask for permission to collect and report this information. To suppress this message:
* To allow collection of data, set the BATECT_ENABLE_TELEMETRY environment variable to 'true', or run './batect --permanently-enable-telemetry'.
* To prevent collection of data, set the BATECT_ENABLE_TELEMETRY environment variable to 'false', or run './batect --permanently-disable-telemetry'.
```

However, mintty actually *is* an interactive session.

### Steps to reproduce

Run any Batect task on "Git Bash" on Windows.

### Expected behaviour

"Git Bash" / mintty is properly detected as an interactive terminal.

### Actual behaviour

"Git Bash" / mintty is not properly detected as an interactive terminal.

### Version information

```plain text
$ ./batect --version
Batect can collect anonymous environment, usage and performance information.
This information does not include personal or sensitive information, and is used only to help improve Batect.
More information is available at https://batect.dev/privacy, including details of what information is collected and a formal privacy policy.

It looks like Batect is running in a non-interactive session, so it can't ask for permission to collect and report this information. To suppress this message:
* To allow collection of data, set the BATECT_ENABLE_TELEMETRY environment variable to 'true', or run './batect --permanently-enable-telemetry'.
* To prevent collection of data, set the BATECT_ENABLE_TELEMETRY environment variable to 'false', or run './batect --permanently-disable-telemetry'.

No data will be collected for this session.

Batect version:    0.74.0
Built:             2021-09-05 11:50:34 +0000
Built from commit: 882f6c4ba18ab5385373185e0c9e75f928f980ea (commit date: 2021-09-05 20:20:09 +1000)
JVM version:       AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.3
OS version:        Windows 10 10.0 amd64
Docker version:    20.10.8 (API version: 1.41, minimum supported API version: 1.12, commit: 75249d8, operating system: 'linux', experimental: false)
Git version:       2.33.0.windows.2

For documentation and further information on Batect, visit https://github.com/batect/batect.
```

### Any other information

In MinTTY's Wiki there's [some tips](https://github.com/mintty/mintty/wiki/Tips#terminal-type-detection--check-if-running-inside-mintty) how to detect mintty.

**Comment by charleskorn** [comment]
Thanks for the bug report @sschuberth. 

To help me diagnose the problem further, could you please run Batect [with logging enabled](https://batect.dev/docs/reference/cli/#--log-file) and share the full log line with the message `Checking if terminal supports interactivity`? I don't need the whole log file, just that line with the attributes such as `stdoutIsTTY`.

**Comment by sschuberth** [comment]
Here you go:

```
{"@timestamp":"2021-09-12T08:41:03.7008776Z","@message":"Checking if terminal supports interactivity.","@severity":"info","@source":"batect.os.ConsoleInfo","@processId":25480,"@threadId":1,"@threadName":"main","stdoutIsTTY":false,"isTravis":false,"operatingSystem":"Windows","terminalType":"xterm"}
...
"consoleInfo":{"stdinIsTTY":false,"stdoutIsTTY":false,"supportsInteractivity":false,"terminalType":"xterm"}
```

**Comment by charleskorn** [comment]
Thanks for the information, I'll take a look when I get a chance.

**Comment by charleskorn** [comment]
@svishal9 has kindly offered to take a look at fixing this issue. I'm going to copy my investigation notes here for him (and my future self):

* Primary issue is that `ConsoleInfo.stdoutIsTTY` is returning `false`
* This is caused by mintty's stdout not being a terminal recognised by Windows
* The page that @sschuberth linked to above (https://github.com/mintty/mintty/wiki/Tips#terminal-type-detection--check-if-running-inside-mintty) gives some hints on how to work around this - if Windows reports that stdout is not a TTY and the `TERM_PROGRAM` environment variable is set to `mintty`, we should use the "send secondary device attributes" escape sequence to confirm if we really are in a `mintty` terminal, and if so, return `true` from `ConsoleInfo.supportsInteractivity`
