### ISSUE TITLE
Make batect respect JAVA_HOME

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1016]
### Describe the problem you'd like to solve

If a JRE is installed but the `java` executable is not in `PATH`, `batect`will quite with

    Java is not installed or not on your PATH. Please install it and try again.

even if the conventional `JAVA_HOME` environment variable points to a JDK / JRE installation.

### Describe the solution you'd like

I'd like the batect scripts for Windows and Linux to take `JAVA_HOME` into account when looking for a Java installation.

### Describe alternatives you've considered

Of course, an alternative is to add the Java installation directory to `PATH`, but that's slightly less convenient when often switching between Java versions.

### Additional context

Some thought needs to be put into the question which Java installation should take precedence if there's both one in `PATH` and `JAVA_HOME` pointing to (another) one.

**Comment by charleskorn** [comment]
Makes sense to me, thanks for the suggestion @sschuberth.
