### ISSUE TITLE
Remove testapp-specific spotless configuration?

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1018]
### Describe the problem you'd like to solve

While converting Groovy to Kotlin, I came across

https://github.com/batect/batect/blob/8498dde8af163558dfd83ff4f0d7f6d80f1d1a5a/wrapper/testapp/build.gradle#L39-L50

which seems to duplicate global configuration done elsewhere in the project, like in [spotless.gradle](https://github.com/batect/batect/blob/main/gradle/spotless.gradle) or [KotlinPlugin.kt](https://github.com/batect/batect/blob/main/buildSrc/src/main/kotlin/batect.buildtools/KotlinPlugin.kt).

### Describe the solution you'd like

Remove this code in favor of global configuration, if possible.

**Comment by charleskorn** [comment]
It's certainly similar to the existing configuration in those places, however this is the only place where we need to configure Spotless to deal with Java. If this is something that can easily be configured for all languages, then I'd certainly be open to a PR for that.

**Comment by sschuberth** [comment]
If this is the only place to deal with Java (i.e. no other Java code requires a different configuration), can't this then simply be moved as `format "Java"` to `spotless.gradle`? And do the same for the Spotless code in `KotlinPlugin.kt`? It seems odd to me to configure Spotless in three different places instead of a single one.

**Comment by charleskorn** [comment]
I believe Spotless doesn't support that, but I might be wrong - I'm 95% sure the configuration needs to be applied to each project rather than being able to be applied to the project globally.

**Comment by sschuberth** [comment]
Thanks for addressing this!
