### ISSUE TITLE
Allow the default value of expression to refer to environment variables

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1019]
### Describe the problem you'd like to solve

I'd like to specify a sub-directory of the host user's home directory as the `local` source directory for a volume. As a `~` prefix did not seem to work, I was trying to use an [expression](https://batect.dev/docs/reference/config/expressions#environment-variables) like `local: ${HOME:-$USERPROFILE}/.gradle` (so `$HOME` is tried first, assuming the host is a Linux system; otherwise assume the host is Windows, and use `$USERPROFILE`). But that does not seem to work either, the "nested" `$USERPROFILE` environment variable does not seem to get resolved.

### Describe the solution you'd like

Environment variables that are part of the *default* value of an expression should be resolved.

### Describe alternatives you've considered

Alternatively / additionally, a dedicated syntax to refer to the current user's home on the host system in a platform-agnostic way, like using `~`, would be nice.

### Additional context

Note that in Bash, `echo ${HOME:-$USERPROFILE}` actually works, so I was assuming it to work with Batect, too.

**Comment by sschuberth** [comment]
> Environment variables that are part of the _default_ value of an expression should be resolved.

This seems to be the code that would need to get touched for this:

https://github.com/batect/batect/blob/8498dde8af163558dfd83ff4f0d7f6d80f1d1a5a/app/src/main/kotlin/batect/config/Expression.kt#L255

**Comment by charleskorn** [comment]
Thanks for the suggestion @sschuberth. Have you seen #990? I'm planning on replacing the current expression syntax with something that would support this far more naturally.

**Comment by charleskorn** [comment]
> a dedicated syntax to refer to the current user's home on the host system in a platform-agnostic way, like using ~, would be nice

This is supported in places that accept local file paths (eg. the local side of a volume mount). Are there other places that you'd like to use it?

**Comment by sschuberth** [comment]
> Have you seen #990?

Ah, no, I didn't connect "expression" with "environment variable" in that context. Thanks for pointing this out to me.

> This is supported in places that accept local file paths (eg. the local side of a volume mount).

Hmm, when I tried it did not seem to work for me on Windows. Is `~`-resolution maybe implemented only on platforms where the shell usually supports it (i.e. on non-Windows)?

> Are there other places that you'd like to use it?

Nope, not yet 😉

**Comment by charleskorn** [comment]
>Is ~-resolution maybe implemented only on platforms where the shell usually supports it (i.e. on non-Windows)?

It should be happening on all platforms - and if it's not, that's a bug :)

**Comment by sschuberth** [comment]
Is there a way to see in the log what `local` paths Batect resolves to?

**Comment by charleskorn** [comment]
You should be able to see the resolved paths for volume mounts in the creation request sent to the Docker daemon, which is logged [here](https://github.com/batect/batect/blob/bcaa3d64ad054174f8b794b16cb457de772c388a/libs/docker-client/src/main/kotlin/batect/docker/api/ContainersAPI.kt#L64).

**Comment by sschuberth** [comment]
Ok, I'm getting

    {"type":"batect.docker.DockerVolumeMountSource.LocalPath","formatted":"C:\\Users\\sebastian\\.gradle","path":"C:\\Users\\sebastian\\.gradle"}

which actually looks good, and using `~` in front of a `local` path on Windows seems to resolve to the user home correctly.

**Comment by sschuberth** [comment]
> > Have you seen #990?
> 
> Ah, no, I didn't connect "expression" with "environment variable" in that context. Thanks for pointing this out to me.

So, since the [table](https://github.com/batect/batect/blob/rfc-2021-01-expressions/rfcs/2021-01-expressions/proposal.md#new-expression-syntax) in the RFC has an entry for "Reference to environment variable with default from other environment variable" (and my immediate use-case would be solved with `~`) I'm closing this in favor of waiting for the new expression syntax.
