### ISSUE TITLE
Allow to disable telemetry from `batect.yml`

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1028]
### Describe the problem you'd like to solve

As Batect can nicely be bootstrapped, it works out of the box even for people new to Batect. However, new users still need to explicitly opt-in/-out from collecting telemetry, which may seem inconvenient.

### Describe the solution you'd like

I'd like to pre-configure the collection of telemetry on a per-project basis via a setting in `batect.yml`. This has two benefits:

1. when Batect is bootstrapped / run for the first time, no annoying hint about telemetry appears, and
2. collection of telemetry can be configured on a per-project basis, so you can allow telemetry collection for some projects, and disallow it for other projects for the same user.

**Comment by charleskorn** [comment]
Thanks for the suggestion @sschuberth. 

I can see value in having something that disables telemetry for a project even if a user has enabled it, however, I'm not keen to add something that enables telemetry automatically with no user intervention - that seems like something that a user should still have control over. Does that make sense?

**Comment by sschuberth** [comment]
Yes, makes sense. So essentially, the idea would be to only allow to disable telemetry from `batect.yml`, but not to enable it.

**Comment by sschuberth** [comment]
So, how would you go for implementing this, @charleskorn? In particular, where exactly inside `batect.yml` should this be configured? Should we allow the user to add a special entry to `config_variables` to disable telemetry?

**Comment by charleskorn** [comment]
I was thinking it could be a top-level configuration option in `batect.yml`, similar to [`project_name`](https://batect.dev/docs/reference/config/#project_name). Something like `forbid_telemetry` perhaps? 

I'm keen to keep config variables for users to do with as they wish.

What do you think?

**Comment by charleskorn** [comment]
Thanks for catching this @sschuberth - I've fixed this issue and it will be included in the next release.

**Comment by sschuberth** [comment]
Awesome @charleskorn, thanks for the follow-up fix and new release!
