### ISSUE TITLE
Consider replacing the `jnr-posix` dependency with Kotlin's `platform.posix.*`

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1032]
### Describe the problem you'd like to solve

In order to get rid of move Java-only dependencies, I was looking at possible alternatives to the `jnr-posix` dependency.

### Describe the solution you'd like

Using Kotlin's own `platform.posix.*` as outlines in [this answer](https://stackoverflow.com/a/67358378/1127485) seems like a solution.

### Additional context

Also see [this roadmap item](https://github.com/batect/batect/blob/main/ROADMAP.md#things-that-would-have-to-be-changed-when-moving-to-kotlinnative).

**Comment by charleskorn** [comment]
Hi @sschuberth, thanks for the suggestion. `platform.posix.*` is only available on Kotlin/Native, so unfortunately we can't remove the dependency on `jnr-posix` - `jnr-posix` will always be required while Batect targets Kotlin/JVM. 

It would definitely make sense to use `platform.posix.*` when we start migrating to Kotlin/Native.
