### ISSUE TITLE
Add a `build_tag` option to containers

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1089]
### Describe the problem you'd like to solve

I'm like to make use of the image built by Batect with plain Docker.

### Describe the solution you'd like

My proposal is to add a `build_tag` option to the [container configuration](https://batect.dev/docs/reference/config/containers) which, when used with `build_directory`, will tag the image built from `<build_directory>/Dockerfile` with `<build_tag>`.

### Describe alternatives you've considered

I guess I could theoretically determine the has of the built image and use that; but that's much more inconvenient than using a tag name.

### Additional context

For debugging, I'd like to be able to run the Docker image implicitly created by Batect when `build_directory` (as opposed to `image`) is specified with plain `docker run`. For this, it would be convenient if I could simply use a tag name to specific the image.

**Comment by charleskorn** [comment]
Hi @sschuberth, thanks for the suggestion. Are you aware that any built images are automatically tagged in the format `<project name>-<container name>`? For example, if you have an image built for the `database` container in a project called `my-project`, the image will be tagged as `my-project-database` automatically.

Furthermore, there's also the [`--tag-image`](https://batect.dev/docs/reference/cli/#--tag-image) CLI option. 

Are those sufficient for your use case, or do you think the configuration option is still valuable on top of those two features?

**Comment by sschuberth** [comment]
> Are you aware that any built images are automatically tagged in the format `<project name>-<container name>`?

No, I wasn't aware of that. Is that documented anywhere? I would have expected it to be mentioned as part of https://batect.dev/docs/reference/config/containers/#build_directory or https://batect.dev/docs/reference/config/containers/#dockerfile.

> Are those sufficient for your use case

Yes, thank you, that auto-generated tag is sufficient for my use-case.

**Comment by charleskorn** [comment]
> Is that documented anywhere as part of the container docs?

No, good catch - I've just added that.

**Comment by thiagoolsilva** [comment]
@charleskorn is it possible to delete untagged image after the batect build it and avoid left untagged images on host computer?

**Comment by charleskorn** [comment]
@thiagoolsilva, I'll answer this over in #1368.
