### ISSUE TITLE
Allow the git include configuration to also download git submodules

### ISSUE THREAD

**Issue by Mknight492** [batect/batect#1131]
### Describe the problem you'd like to solve

I'm trying to setup a multi-repo application to use Batect to orchestrate local development and CI Docker containers.
Currently we use PowerShell scripts and Nuget packages to do this.

We have a core repo which hold all the utilities and in this repo there is currently a PowerShell script which will download all the Nuget Packages and images for the other repos and run them locally.

I'd like to use the Batect include functionality instead so that each repo can have it's own batect-bundle which informs the root project how to deploy it's containers etc.

The issue is that the our repos depend on Submodules and these aren't downloaded with the `include - type git` configuration so the tasks fail.

### Describe the solution you'd like

An additional piece of configuration which allows you to also pull down submodules when doing an includes git.

**Comment by charleskorn** [comment]
Thanks for the suggestion @Mknight492. So you'd like Batect to run something like `git submodule update --init --recursive` after cloning the bundle?

**Comment by Mknight492** [comment]
Hi @charleskorn, sorry about the delaying getting back to you but yes that's exactly what I'm referring to. I had a brief look at the source code and I could raise a PR if there's some interesting in adding the feature?

**Comment by charleskorn** [comment]
No worries at all. A PR would be great. Let me know if you have any questions or need any help.

**Comment by charleskorn** [comment]
Hey @Mknight492, are you still interested in putting together a PR for this?
