### ISSUE TITLE
Batect should use BuildKit if it's enabled globally

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1156]
### Describe the bug

I've [enabled BuildKit globally](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds) via `/etc/docker/daemon.json` and as such would expect Batect to make use of it, but I get `Building image failed: the --mount option requires BuildKit`.

### Reproduction repo

https://github.com/oss-review-toolkit/ort/tree/batect

### Steps to reproduce

`./batect gradle -- tasks`

### Expected behaviour

Batect should have BuildKit support enabled by default if BuildKit is enabled globally.

### Actual behaviour

Batect requires explicit enabling of BuildKit even if BuildKit is already enabled globally.

### Version information

```plain text
Batect version:    0.77.2
Built:             2022-01-07 10:29:26 +0000
Built from commit: c182480de673b1c118f483cd54b2c94c399b3129 (commit date: 2022-01-07 20:22:09 +1100)
JVM version:       Ubuntu OpenJDK 64-Bit Server VM 11.0.13
OS version:        Linux 5.4.0-94-generic amd64 (Ubuntu 18.04.6 LTS (bionic))
Docker version:    20.10.12 (API version: 1.41, minimum supported API version: 1.12, commit: 459d0df, operating system: 'linux', experimental: false)
Git version:       2.34.1
```

### Any other information

~Maybe Batect should also directly adhere to Docker's own `DOCKER_BUILDKIT` environment variable.~

*Edit:* That's already the case, see https://batect.dev/docs/how-to/performance/#use-buildkit.

**Comment by sschuberth** [comment]
I couldn't find a way to ask Docker whether BuildKit is enabled, so my best idea currently is to simply parse `/etc/docker/daemon.json` (if `DOCKER_BUILDKIT` is unset).

**Comment by charleskorn** [comment]
Thanks for the report @sschuberth.

The `DOCKER_BUILDKIT` environment variable should already be respected - are you not seeing this behaviour?

> I couldn't find a way to ask Docker whether BuildKit is enabled, so my best idea currently is to simply parse `/etc/docker/daemon.json` (if `DOCKER_BUILDKIT` is unset).

The Docker daemon does expose this information (albeit in a slightly unexpected way): performing a `HTTP GET /_ping` should return a `Builder-Version` header indicating the daemon's preferred builder, either the legacy builder or BuildKit. 

Batect has (up until now) been ignoring this and always defaults to the legacy builder. This was to give time to prove Batect's BuildKit support was stable, but I'm not aware of any significant issues with it, so I'd be happy to start respecting this setting.

**Comment by sschuberth** [comment]
> The `DOCKER_BUILDKIT` environment variable should already be respected - are you not seeing this behaviour?

I *do* see that behavior, see the edited "Any other information" in my original post.

> so I'd be happy to start respecting this setting.

👍🏻

**Comment by charleskorn** [comment]
I've just made this change and will release a new version shortly - thanks for the report @sschuberth!.
