### ISSUE TITLE
Complaint whilst building Batect project -- wrapper:windows:build ... execution optimizations have been disabled

### ISSUE THREAD

**Issue by binkley** [batect/batect#1159]
### Describe the bug

(Apologies that marked in GitHub labels as "is:bug" -- I'm unsure how to mark this correctly.)

I'm not sure if I should care about this warning during build of Batect's code base.  Yeah, I'm not on Windows, but as a matter of general principles, I'd like to see **No build warnings**.  Note: no diffs with `upstream/main`.

Is there anything I can do to improve this (possibly a PR)?

```
> Task :wrapper:windows:build
Execution optimizations have been disabled for task ':wrapper:windows:build' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/boxley/src/batect/app/build/libs/batect-0.78.0-dev.0.5+4b8ae0b.jar'. Reason: Task ':wrapper:windows:build' uses this output of task ':app:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

### Reproduction repo

Current local repo is up-to-date with `upstream/main`
`git diff HEAD upstream/main` shows no changes

### Steps to reproduce

$ git fetch upstream/main
$ git merge upstream/main
$ ./gradlew clean build

### Expected behaviour

Fewer complaints during build, **else** fail build for unexpected complaints.

### Actual behaviour

This complaint from Gradle:
```
> Task :wrapper:windows:build
Execution optimizations have been disabled for task ':wrapper:windows:build' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/boxley/src/batect/app/build/libs/batect-0.78.0-dev.0.5+4b8ae0b.jar'. Reason: Task ':wrapper:windows:build' uses this output of task ':app:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

### Version information

```plain text
N/A -- using the build from tip of Batect repo
```

### Any other information

I'm unclear if `./gradlew clean build` uses the Docker images for Windows and other platforms from within a local clone of the Batect repo while building (I need to watch the output more closely: this might be me, not you): it is not clear from the Gradle output.

Perhaps fuller instructions in GitHub `README.md` along the lines of Yegor's _Elegant READMEs_ doc would help (ref: https://www.yegor256.com/2019/04/23/elegant-readme.html) to make it easier for contributors.

**Comment by charleskorn** [comment]
Thanks for the report @binkley. 

I believe this is an issue with the Shadow plugin: https://github.com/johnrengelman/shadow/issues/713. 

Running `./gradlew --warning-mode=all clean build` shows a number of warnings from that plugin's tasks. If you were interested in fixing this, I'd suggest starting there.
