### ISSUE TITLE
feat: support output image in iterm2

### ISSUE THREAD

**Issue by yuzhanglong** [batect/batect#1189]
### Describe the problem you'd like to solve

thanks for the awesome project！
And I Have feature request：
some script can output image in iterm:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/56540811/156881471-03d6b60b-f90e-4390-ba45-b00b8e688bdf.png">

but when run the script by batect in iterm, it will not work:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/56540811/156881424-21fbf781-a5fd-4ee8-933b-738d1ec4935d.png">

### Describe the solution you'd like

can you support it 😄， thanks~

**Comment by charleskorn** [comment]
Hi @yuzhanglong, thanks for reporting this issue. 

Could you please share a simple sample repository that demonstrates this issue?

**Comment by yuzhanglong** [comment]
> Hi @yuzhanglong, thanks for reporting this issue.
> 
> Could you please share a simple sample repository that demonstrates this issue?

Thanks for your reply, I have found a solution, It is not batect's problem :
- [ the image output library](https://github.com/sindresorhus/term-img) I used will determine the operating system of the current operating environment, if not MacOS will not output the image. because Item2 is macos software.
- But whether or not you can print an image depends on what the command line says，If I run docker in macos + Iterm2, the docker env is not macos, so the library will not work.
- The solution is to use: [ansi-escapes ](https://www.npmjs.com/package/ansi-escapes)
