### ISSUE TITLE
shared tmpfs volume support

### ISSUE THREAD

**Issue by flo-everett-xero** [batect/batect#1253]
### Describe the problem you'd like to solve

Hi, I'd like to share a file that is created by a prerequisite task with the final task. the contents of this file have no meaning outside of the context of the overall task, and so there is no reason to persist the contents of this file on disk after the task has finished. this seems like the perfect candidate for a tmpfs volume mount

### Describe the solution you'd like

I would like to be able to define a tmpfs volume mount on a container (or task), which is then accessible from any other containers or tasks within an overall task definition. It could then destroy itself when the task finishes

### Describe alternatives you've considered

a .gitignored folder

**Comment by charleskorn** [comment]
Hi @flo-everett-xero, thanks for the suggestion.

[Docker's tmpfs mounts](https://docs.docker.com/storage/tmpfs/) don't support sharing between containers - a tmpfs mount can only be used by a single container, and they're then destroyed when the container exits.

However, [Batect's caches](https://batect.dev/docs/concepts/caches/) might do what you're looking for - have you tried using a cache?
