### ISSUE TITLE
Included file '' from '' does not exist

### ISSUE THREAD

**Issue by isaac-patterson** [batect/batect#1256]
### Describe the bug

Weird local setup issue it seems? The following code works great on all engineers laptops except one! This error is thrown when trying to include a bundle (cloned via ssh)

```yml
include:
  - type: git
    repo: git@xxx.git
    ref: 690b6350694339898b0ff5a6ce77a3ddb91ce44d
    path: bundles/linting/linting-bundle.yml
```

```
C:\Dev\xxxbatect.yml: Included file 'bundles/linting/linting-bundle.yml' (bundles/linting/linting-bundle.yml from git@xxx.git@690b6350694339898b0ff5a6ce77a3ddb91ce44d) does not exist.
```

### Steps to reproduce

Docker version 20.10.12, build e91ed57

java 18.0.1.1 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

Microsoft Windows 10 Enterprise - 10.0.19043 Build 19043

### Expected behaviour

Bundle containers and tasks are included in our batect project

### Actual behaviour

```
C:\Dev\xxxbatect.yml: Included file 'bundles/linting/linting-bundle.yml' (bundles/linting/linting-bundle.yml from git@xxx.git@690b6350694339898b0ff5a6ce77a3ddb91ce44d) does not exist.
```

### Version information

```plain text
Batect version:    0.78.0
Built:             2022-01-16 03:23:47 +0000
Built from commit: 4f150cf845b34db7fd0d8842800511679ee5d4bf (commit date: 2022-01-16 13:41:55 +1100)
JVM version:       Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 18.0.1.1
OS version:        Windows 10 10.0 amd64
Docker version:    20.10.12 (API version: 1.41, minimum supported API version: 1.12, commit: 459d0df, operating system: 'linux', experimental: false)
Git version:       2.33.1.windows.1
```

**Comment by charleskorn** [comment]
That sounds like a corrupted local version of the bundle... can you try removing the contents of `~/.batect/incl` and try again? (On Windows, I believe this will be something like `C:\Users\<user>\.batect\incl`, but I'm not near a Windows machine right now to check.)

**Comment by isaac-patterson** [comment]
Yes that was it! learnt something new today :) this was because the ssh key wasnt setup properly initially. So it must of created the folder but not populated it. Closing this issue
