### ISSUE TITLE
Unable to pull images when using a private docker image registry that requires login.

### ISSUE THREAD

**Issue by Bidaya0** [batect/batect#1261]
### Describe the bug

Pulling image '****' failed: pull access denied for ***, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### Steps to reproduce

1. use private docker image registry
2. run batect task.

### Expected behaviour

It works fine when docker is logged in

### Actual behaviour

```
 repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

### Version information

```plain text
Batect version:    0.79.1
Built:             2022-04-24 05:04:00 +0000
Built from commit: a33d32f6303e3905e6fe57178dc4f4dadc3ab15d (commit date: 2022-04-24 14:28:58 +1000)
JVM version:       Debian OpenJDK 64-Bit Server VM 11.0.14
OS version:        Linux 5.10.0-11-amd64 amd64 (Debian GNU/Linux 11 (bullseye) (debian))
Docker version:    20.10.12 (API version: 1.41, minimum supported API version: 1.12, commit: 459d0df, operating system: 'linux', experimental: false)
Git version:       2.30.2
```

**Comment by charleskorn** [comment]
Hi @Bidaya0, pulling images from private registries is supported by Batect, so I'm surprised to see this.

If you try to pull the image with `docker pull ...`, does it work?

**Comment by Bidaya0** [comment]
> Hi @Bidaya0, pulling images from private registries is supported by Batect, so I'm surprised to see this.
> 
> If you try to pull the image with `docker pull ...`, does it work?

it work with `docker pull `.
it failed when I use 
```
image_pull_policy: Always
```

In fact, my temporary solution now is   `docker pull` first and then use batect to start

**Comment by charleskorn** [comment]
Without more information, it's going to be hard for me to understand what's happening.

Are you able to tell me a little bit more about your private image registry? Are you using something like AWS ECR or Artifactory?

Are there entries for your image registry in the `auths` key in `~/.docker/config.json`?

Also, if you run Batect with logging enabled (`./batect --log-file=log.json ...`), are there any log messages related to image registry authentication?

**Comment by Bidaya0** [comment]
Can you tell me which parts of log.json will have sensitive information? I need to deal with it and post it, I see some Exceptions in it.

**Comment by Bidaya0** [comment]
@charleskorn  
I'm using alibaba cloud's docker registry, and I don't know the specific differences between their implementations.

**Comment by Bidaya0** [comment]
[Uploading log.json.zip…]()

**Comment by Bidaya0** [comment]
> [log.json.zip](https://github.com/batect/batect/files/8761247/log.json.zip)

log.json file here.
@charleskorn

**Comment by charleskorn** [comment]
OK, in your `~/.docker/config.json` file, you should have something like this:

```json
{
	"auths": {
		"registry.cn-beijing.aliyuncs.com": { "auth": "xxx" },
		"https://index.docker.io/v1/": { "auth": "yyy" }
	}
}
```

If you base64-decode those `auth` values, you should get your credentials for those repositories (try something like `echo -n "xxxx" | base64 --decode` to view them). Do the credentials look right to you?

(Please don't post the encoded or decoded values here 😃)

**Comment by Bidaya0** [comment]
> 

I don't have this file in my system, do I need to create it manually, generally, `docker login` is valid

> OK, in your `~/.docker/config.json` file, you should have something like this:
> 
> ```json
> {
> 	"auths": {
> 		"registry.cn-beijing.aliyuncs.com": { "auth": "xxx" },
> 		"https://index.docker.io/v1/": { "auth": "yyy" }
> 	}
> }
> ```
> 
> If you base64-decode those `auth` values, you should get your credentials for those repositories (try something like `echo -n "xxxx" | base64 --decode` to view them). Do the credentials look right to you?
> 
> (Please don't post the encoded or decoded values here smiley)

I don't have this file in my system, do I need to create it manually？strangely, the `docker login` works well

```
➜  ~ docker --version
Docker version 20.10.12, build e91ed57
```

**Comment by charleskorn** [comment]
According to the log file, Batect is using a configuration file from `/root/.docker/config.json` - does that exist?

**Comment by charleskorn** [comment]
Are you running some commands with `sudo` and some without by any chance? Docker registry credentials are stored per-user, so any credentials stored for your user won't be used when running commands as `root` with `sudo`.
