### ISSUE TITLE
Disable progress output when downloading / bootstrapping Batect

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1330]
### Describe the problem you'd like to solve

I'd like to get rid of broken progress indicators when bootstrapping Batect in CI builds.

### Describe the solution you'd like

An option to the Batect script to disable progress output when downloading / bootstrapping the Batect distribution.

### Describe alternatives you've considered

One could do a "dummy run" of Batect to bootstrap itself and pipe all output of that run to `/dev/null`, and then do the real run which then does not require bootstrapping anymore, but that's really not nice.

### Additional context

See e.g. log output starting at https://github.com/oss-review-toolkit/ort/runs/8056553739?check_suite_focus=true#step:7:9.

**Comment by charleskorn** [comment]
Thanks for the suggestion @sschuberth. Have you tried setting the `BATECT_QUIET_DOWNLOAD` environment variable to `true`? This should silence the progress output during downloads.

**Comment by sschuberth** [comment]
> Have you tried setting the `BATECT_QUIET_DOWNLOAD` environment variable to `true`?

Now I [have](https://github.com/oss-review-toolkit/ort/pull/5705) 😀 I was only looking for CLI options to do that so far; thanks for pointing out the environment variable!
