### ISSUE TITLE
Migrate from Spek / Hamkrest to Kotest / MockK?

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1334]
### Describe the problem you'd like to solve

I'd like to get consistency into the test framework(s) being used.

### Describe the solution you'd like

Settle on either Spek / Hamkrest or Kotest / MockK, but esp. do not use Spek and Kotest in the same tests.

### Additional context

While working on https://github.com/batect/batect/pull/1332 it had confused me why multiple dependencies that serve the same purpose are being used.

**Comment by charleskorn** [comment]
Thanks for the suggestion @sschuberth. This is something I've been wanting to do for a while, but haven't had the time to.

I'd prefer to migrate to Kotest as it is more actively maintained and supports Kotlin/Native.

I'm not sure I'd link Kotest and MockK though - I don't see anything stopping us from using Hamkrest and Kotest together.

In terms of migration steps, I was thinking this could be done gradually, starting with switching assertions from using Hamkrest to Kotest equivalents, then migrating the test framework from Spek to Kotest. I've had good experience with using something like [Comby](https://comby.dev/) to do this in an automated fashion in the past.

> do not use Spek and Kotest in the same tests

I don't believe there are any examples of this - have you come across this? Almost all of the tests should be using Spek and Hamkrest with the exception of the journey tests.

**Comment by sschuberth** [comment]
> I'd prefer to migrate to Kotest as it is more actively maintained and supports Kotlin/Native.

Just to clarify, more actively maintained than Spek, that is, right?

> I'm not sure I'd link Kotest and MockK though - I don't see anything stopping us from using Hamkrest and Kotest together.

Kotest comes with its own matchers, so I don't see a reason to use Hamkrest. MockK, on the other hand, complements Kotest with mocking for unit tests.

> starting with switching assertions from using Hamkrest to Kotest equivalents, then migrating the test framework from Spek to Kotest.

Makes sense to me, though I believe the order could also be swapped.

> I've had good experiences using something like [Comby](https://comby.dev/) to do this in an automated fashion in the past.

Comby looks interesting, thanks for pointing it out. On the topic of "mass refactoring" I was looking at https://github.com/openrewrite/rewrite so far.

> Almost all of the tests should be using Spek and Hamkrest with the exception of the journey tests.

It's the journey tests I was referring to. These seem to use Spek as the framework, but Kotest matchers / assertions.

**Comment by charleskorn** [comment]
> Just to clarify, more actively maintained than Spek, that is, right?

Yep, that's what I meant.

> Kotest comes with its own matchers, so I don't see a reason to use Hamkrest. MockK, on the other hand, complements Kotest with mocking for unit tests.

Sorry, I meant to say "I'm not sure I'd link Kotest and MockK though - I don't see anything stopping us from using **Mockito** and Kotest together."

**Comment by sschuberth** [comment]
> Sorry, I meant to say "I'm not sure I'd link Kotest and MockK though - I don't see anything stopping us from using **Mockito** and Kotest together."

Ah, right. There's indeed no technical blocker to use / continue using Mockito. It's just that MockK is written in Kotlin (🎉) and thus there's a [chance for Kotlin/Native support](https://github.com/mockk/mockk/issues/58).
