### ISSUE TITLE
Linux containers sometimes fail to start on Windows when using Docker 4.12+

### ISSUE THREAD

**Issue by MichaelKnightXero** [batect/batect#1344]
### Describe the bug

While trying to use the dependencies for a task batect isn't waiting for the dependencies to pass health checks.

![batect_error](https://user-images.githubusercontent.com/112362709/188560503-e5f33bce-3cb9-455b-9b57-c92f8106eaa3.gif)

### Reproduction repo

given the following batect.yml

```
containers:
  postgres:
    image: postgres:12.8-alpine

  redis:
    image: redis:6-alpine

tasks:
  run:test:
    description: Run task with dependencies
    group: Run tasks
    dependencies:
      - redis
    run:
      container: postgres
```

### Steps to reproduce

run the following command ` ./batect --log-file  batect_logfile run:test`

output

```
Running run:test...
redis: starting container...
postgres: waiting for dependency redis to be ready...

Error: Could not run container redis.
The pipe is being closed.

Clean up: done

The task run:test failed. See above for details.
``` 

### Expected behaviour

tasks wait for redis to start

### Actual behaviour

batect fails to wait for less than the docker defaults for healthchecks and fails within a second.

### Version information

```plain text
batect version:

Batect version:    0.81.0
Built:             2022-09-05 06:19:30 +0000
Built from commit: 488e0911965172593db201f4be65a374d0e45e4c (commit date: 2022-09-05 15:44:52 +1000)
JVM version:       Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_341
OS version:        Windows 10 10.0 amd64
Docker version:    20.10.17 (API version: 1.41, minimum supported API version: 1.12, commit: a89b842, operating system: 'linux', architecture: 'amd64', experimental: true)
Git version:       2.33.1.windows.1

OS: Windows 10 Enterprise version 21H2

Java version:
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

Docker version: (running WSL-2)

Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      false

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Any other information

unable to attach batect logs due to length, can share by alternative method if required

**Comment by MichaelKnightXero** [comment]
I'm see this in the logs for what it's worth:

{"@timestamp":"2022-09-06T06:20:07.268Z","@message":"Running container failed.","@severity":"error","@source":"batect.execution.model.steps.runners.RunContainerStepRunner","@processId":20076,"@threadId":24,"@threadName":"pool-1-thread-6","exception":"batect.dockerclient.AttachToContainerFailedException: The pipe is being closed.\r\n\tat batect.dockerclient.RealDockerClient$attachToContainerIO$2$1$1$1$4$1.invoke(RealDockerClient.kt:343)\r\n\tat batect.dockerclient.RealDockerClient$attachToContainerIO$2$1$1$1$4$1.invoke(RealDockerClient.kt:338)\r\n\tat batect.dockerclient.native.ExtensionsKt.ifFailed(Extensions.kt:341)\r\n\tat batect.dockerclient.RealDockerClient$attachToContainerIO$2$1$1$1$4.invoke(RealDockerClient.kt:338)\r\n\tat batect.dockerclient.RealDockerClient$attachToContainerIO$2$1$1$1$4.invoke(RealDockerClient.kt:328)\r\n\tat batect.dockerclient.GolangContextKt$launchWithGolangContext$2$1.invokeSuspend(GolangContext.kt:34)\r\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\r\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)\r\n\tat kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)\r\n\tat kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)\r\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)\r\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)\r\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)\r\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)\r\n","containerId":"a9c1306599b2766ed76b44c87c25a7045b1dea12e8ff63bb22cbbb147e0eaf42"}

**Comment by charleskorn** [comment]
Thanks for the bug report @MichaelKnightXero. 

Are there any other errors in the logs? (If you'd rather not trawl through them yourself, feel free to either attach them here or send them to me privately at me@charleskorn.com.)

**Comment by MichaelKnightXero** [comment]
I'll send them through, I can't see any other errors or exceptions in the logs though

**Comment by charleskorn** [comment]
Thanks for sharing the logs. I can't see any clues in there, and I'm not able to reproduce this issue myself either unfortunately.

Is there any other information that might help me reproduce the issue?

For example, does this happen consistently for you? Or does it only happen sometimes?

Also, what shell and terminal are you using? (eg. PowerShell in the Windows Terminal app, or Git Bash in the default Windows Command Prompt app)

**Comment by MichaelKnightXero** [comment]
Yeah I'm not surprised it's hard to repo.

The error only happens intermittently but very frequently.


 I'm using the following powershell: 
 
 Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682


However I also get the same error when running when running it from Git Bash.

It all seem to occur less frequently when I run it with the --output=all flag

and if I run batect with version 0.78 I will consistently get the following error:

most recently I've also seen the following error

```
 Batect | During execution of step of kind 'RunContainerStep': java.util.concurrent.ExecutionException: batect.os.WindowsNativeMethodException: Invoking native method GetOverlappedResult failed with error ERROR_BROKEN_PIPE (The pipe has been ended).
 ```
 
 I'm not sure what the next steps are but I'm happy to try and help where possible

**Comment by charleskorn** [comment]
The `Invoking native method GetOverlappedResult failed with error ERROR_BROKEN_PIPE (The pipe has been ended).` error was an issue in the pre-v0.80 Docker client that Batect used, so I _think_ that's unrelated.

I'll keep digging and see if I can come up with any other theories as to why this might be happening, and let you know if I need any more information. Thanks for your patience!

**Comment by MichaelKnightXero** [comment]
My current theory (for what it's worth) is that it's failing to connect to the docker containers and it's throwing an unhandled error and causes the process to end instead of waiting for the container to be ready. But I don't really know how to debug or investigate it given I'm not very familiar with the toolchain.

**Comment by charleskorn** [comment]
> My current theory (for what it's worth) is that it's failing to connect to the docker containers and it's throwing an unhandled error and causes the process to end instead of waiting for the container to be ready. 

Yep, that's exactly what's happening - the issue isn't starting the container, but attaching to it to stream input and output to/from it. Once attaching fails, Batect bails out rather than trying to continue.

> Are there any other settings that I could have configured for WSL, Docker or Java that could be relevant?

I don't think so - at least I don't have any ideas until we can nail down what's causing this. I've had the task running on a loop all day on my Windows laptop and it's worked flawlessly every time :confused:

Out of interest, if you change your config to only run the Redis container, do you run into the same problem? Or is it only when there's a dependency relationship involved? 

ie. do you see the same issue if you use this config?

```yaml
containers:
  redis:
    image: redis:6-alpine

tasks:
  run:test:
    description: Run task with dependencies
    group: Run tasks
    run:
      container: redis
```

**Comment by MichaelKnightXero** [comment]
It does actually happen with just a single container running:

![image](https://user-images.githubusercontent.com/112362709/189211022-2af470d0-6241-4a18-a6f1-570e6ffa220f.png)

Would it be helpful if I setup the batect toolchain and run it locally in debug mode? How difficult might that be to do?

**Comment by charleskorn** [comment]
> It does actually happen with just a single container running:

Interesting... are you able to run the task with logging enabled and share the logs with me?

> Would it be helpful if I setup the batect toolchain and run it locally in debug mode? How difficult might that be to do?

Thanks for offering. Debugging Batect as a whole might not be so useful, as I suspect it's not Batect itself but an interaction between the Docker API client Batect uses and Docker. 

If you're keen and have the time, try cloning [docker-client](https://github.com/batect/docker-client) and run `./gradlew jvmTest` (this will take a while the first time). I'd be interested to see which (if any) tests fail and if they fail consistently or if the behaviour is intermittent as well.

**Comment by MichaelKnightXero** [comment]
Ahh I didn't realise you also maintained the docker-client tool. I've run `./gradlew jvmTest` a few times and there are a  number of tests are failing intermittently and they're largely due to issues connecting to the containers, as you'd expect.

I've sent you through the logs and one with the --debug flag test to true. I don' think they get us further though. Would it be useful debugging one of the tests that's failing?

> Interesting... are you able to run the task with logging enabled and share the logs with me?
I haven't done this given it seems it would be more helpful investigating the docker-client library directly, although I'm happy to if you' like me to.

**Comment by charleskorn** [comment]
Thanks for sharing the logs @MichaelKnightXero. I'm a bit snowed under with other things at the moment but I will look at this properly when I get a chance in the next few days.

**Comment by charleskorn** [comment]
It _seems_ like there's an issue with your Docker daemon - a couple of the tests fail in ways that should never happen with a well-behaving daemon (eg. `unable to upgrade to tcp, received 500` and `Error response from daemon: i/o timeout`).

Do you have the same issues if you use the `docker` CLI? For example, does running `docker run --rm -it redis:6-alpine` consistently work?

Also, if you can, it might be interesting to take a look at the Docker daemon's logs to see if there are any clues there. https://docs.docker.com/config/daemon/#read-the-logs shows where the logs are stored.

**Comment by MichaelKnightXero** [comment]
Hey sorry @charleskorn for taking so long to get back to you. I'll be looking into this more next week and update you with the docker-daemon logs etc. I'm guessing it's likely that I may need to raise an issue there instead though presumably?

**Comment by charleskorn** [comment]
No worries @MichaelKnightXero. Let's see what the daemon logs say - it may just be that it's in a bad state and needs to be reinstalled, or there might be something else going on.

**Comment by DanielLoth** [comment]
Hi @charleskorn,

I'm another Xero employee. I don't work with Michael, but encountered this problem today independently.

After doing most of the things described above prior to seeing this thread. After seeing this thread and discovering the ability to write to a log file I was later able to run batect with the logging flag, and only had an error similar to the one shared above.

Ultimately I uninstalled Docker for Windows and reinstalled an older version (4.11.1 84025). I am once again able to run the batect command as I could previously.

So perhaps there's an issue with Docker 4.12.0.

**Comment by charleskorn** [comment]
Interesting, thanks for reporting back @DanielLoth. Do you have the same problems with the `docker` CLI on Docker 4.12? Or is it only with Batect?

**Comment by DanielLoth** [comment]
Hi @charleskorn,

It appeared to just be Batect as I was able to run the following commands via Docker CLI without any issue:
```
docker run -it  --env ACCEPT_EULA=Y --env SA_PASSWORD=Something@strong1 mcr.microsoft.com/mssql/server:2019-latest
docker run -it  --env ACCEPT_EULA=Y --env MSSQL_SA_PASSWORD=Something@strong1 mcr.microsoft.com/mssql/server:2019-latest
```

**Comment by DanielLoth** [comment]
Also, just as an aside, thank you for the very cool tool. This particular issue notwithstanding, Batect has never skipped a beat.

**Comment by charleskorn** [comment]
@DanielLoth 

> It appeared to just be Batect as I was able to run the following commands via Docker CLI without any issue

Weird. Next time this fails with Batect, could you take a look at the Docker daemon's logs (see https://github.com/batect/batect/issues/1344#issuecomment-1246165236) to see if there are any clues in there?

**Comment by MichaelKnightXero** [comment]
Hey @charleskorn, sorry it's been such a long time since I've given an update. 

Essentially there are a few people at Xero who have had the same issue with the latest version of Docker (4.12) which was fixed by downgrading.

I tried to get logging working with the docker daemon but it wasn't that easy to get going. I'm currently not blocked and I don't really have time to investigate it future at the moment sorry so I'm happy to close the issue but it's up to you.

**Comment by charleskorn** [comment]
No worries @MichaelKnightXero, thanks for getting back to me. Let's leave this open until we solve it once and for all.

**Comment by MarwanAwroojXero** [comment]
Hi There, I also Work in Xero and encountered same issue, we are using latest docker but were on batect 0.79.1 and this issue surfaced when we upgraded to 0.8.1 from 0.79.1
I get the same error The pipe is being closed, I have compared docker logs between a run on 0.79 and 0.8.1 see below (0.79 on the left doesn't through an error message when upgrading to raw stream
![image](https://user-images.githubusercontent.com/115607342/195250833-2127e87b-a147-44c3-9ea5-6ae560f609f0.png)
I get this issue consistently on a dependency of SQL server container docker image with health check configured in batect to run some sql query to make sql is up and running.

**Comment by charleskorn** [comment]
Thanks for sending through the logs @MarwanAwroojXero. What is the name of the process that is emitting those log lines (something ending with `.exe`)? It's cut off in your screenshot.

**Comment by MarwanAwroojXero** [comment]
its com.docker.proxy.exe
![image](https://user-images.githubusercontent.com/115607342/196057483-2ef9a1ff-d815-46d1-b42a-5088de929812.png)

**Comment by charleskorn** [comment]
As far as I'm aware, the source code for that process is not open source, so I can't look into what might have changed with Docker for Windows 4.12. Would you be open to raising an issue with Docker directly, explaining what you're seeing? Feel free to tag me in the issue and I'll help out however I can.

**Comment by MarwanAwroojXero** [comment]
Hey Charles, I think this is not an issue with Docker but rather from batect itself, I managed to replicate this issue on my personal pc with Docker running on WSL containers and this basic yml sample file
`project_name: launchpad
containers:
  sample:
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
  sample2:
    image: mcr.microsoft.com/dotnet/samples:aspnetapp

  sample3:
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    dependencies:
      - sample2
tasks:
  sample:
    description: Run Sample
    run:
      container: sample3`

If you run this the first time (i.e.  .\batect sample), when it pull the images, it works fine, however if you run it the second time, 
you get 

_Error: Could not run container sample2.
The pipe is being closed.

Clean up: done_

if I do run .\batect --no-cleanup sample , I do get the error but looking at docker the container is started fine
![image](https://user-images.githubusercontent.com/115607342/208339693-6fe541ed-c0ce-464e-b48d-aafb4f62b80e.png)

It feels like of some timing issue with batect

**Comment by charleskorn** [comment]
Thanks for the reproduction @MarwanAwroojXero. I'll take a look when I get a chance.

**Comment by charleskorn** [comment]
I _think_ I've fixed this and will release a fix shortly. Thanks for your help and patience @MichaelKnightXero @MarwanAwroojXero!
