### ISSUE TITLE
Provide support for Docker outside of Docker while using run_as_current_user

### ISSUE THREAD

**Issue by Malinskiy** [batect/batect#1385]
### Describe the problem you'd like to solve

Executing complex integration tests requires the test itself to declare its dependencies and spin them up e.g. using https://www.testcontainers.org/

### Describe the solution you'd like

An option to add more host user groups to the container should be enough as well

### Describe alternatives you've considered

Boolean flag along the lines of `DooD`, but that is probably a bit too involved

### Additional context

It is not desirable to run the container as root for security reasons, hence the usage of `run_as_current_user`. Unfortunately, it doesn't pass the host's docker group for generating an appropriate `/etc/groups` file, which results in permission denied access to the Unix socket.

The documentation states:
> Again, this means that any other groups defined in the container's image are effectively lost. Under most circumstances, this is not an issue.

I believe this is one of those rare cases where it is desirable to add more groups.

A very quick hacking at this problem shows that for Linux using `jnr.posix.Posix#getgrnam(name)` is sufficient for propagating the docker group id into the generation of the `/etc/groups` in `batect.execution.RunAsCurrentUserConfigurationProvider#generateGroupFile` . The only problem is switching the runtime groups in a session that I was able to do using [newgrp](https://linux.die.net/man/1/newgrp), but there is probably a better solution.

**Comment by charleskorn** [comment]
Hi @Malinskiy, thanks for the suggestion. 

Batect encourages a slightly different approach to integration tests with external dependencies. Rather than having your tests orchestrate dependencies with something like testcontainers, the recommended approach is to use Batect itself to orchestrate them. 

The [Java](https://github.com/batect/batect-sample-java) and [Ruby](https://github.com/batect/batect-sample-ruby) sample projects both demonstrate this approach. 

Does this suit your use case? Or are you trying to achieve something else?

**Comment by Malinskiy** [comment]
No, unfortunately, this doesn't suit the use case because of the side effects external dependencies have. The test itself has to allocate its dependency for multiple reasons, I'll try to provide a couple of examples.
1. Let's say you have a codebase that depends on some form of SQL storage. After the container is spun up each test prepares the initial state of the storage, i.e. schema and basic entries in the tables. These might be different for different tests. For example, one test verifies that migration of the schema succeeds and the other is verifying basic CRUD operations on the latest schema version. Each of such tests needs a separate instance since the tests are executed in parallel. The number of such tests can be in the 100s or 1000s.
2. Let's say that you're testing the initialisation of a multi-service system. Let's say it's a consensus algorithm underneath (something along the lines of Raft). To test such a system I need to manually control the lifecycle of the containers from the test, e.g. spin 1, spin 2, spin 3, check result, remove 2, assert that the result is as expected.

Unless batect provides integration points to ask batect to spin something up from the test code (and this can be a Java framework such as JUnit or golang's testing framework, so multiple clients are needed for a particular ecosystem) this issue is going to be relevant and the easiest solution is just to expose docker API via the docker socket.

Hope this helps understand the use case better @charleskorn

**Comment by charleskorn** [comment]
Right, makes sense. 

Just to clarify, is this only an issue on Linux hosts? Or does it affect macOS hosts as well?

Would something like being able to configure a list of additional group names to propagate into the container for your user work for your use case? I'm imagining something like having `additional_groups` as a list under `run_as_current_user`, and then you could specify `docker`, for example.

**Comment by charleskorn** [comment]
> Additional groups works for this setup as long as it's a string identifier and not the `long` id of the group since on different linux OSes the id can be different for the `docker` group.

Perfect, that's exactly what I'm thinking (a list of group names, not a list of group IDs). 

I will be travelling for the next week and a bit, so I'm not likely to have time to do this myself in the next little while unfortunately. I'm happy to have a look when I get a chance, or I'm also happy to provide some pointers and feedback on a PR if you're keen to have a go at this yourself.

**Comment by charleskorn** [comment]
Just been thinking about this a little more @Malinskiy. If one of the groups listed under `additional_groups` doesn't exist on the host, what should the behaviour be? Batect could either ignore the group, add the group with a random group ID, or show an error and not start the container.

I can see pros and cons to each approach depending on the scenario - what do you think?

**Comment by Malinskiy** [comment]
My personal view on this is the code should fail fast, so if the group specified is missing - fail the build as soon as possible. otherwise, you risk having undefined behaviour.
The purpose of this parameter will always be granting permissions to some group, if it's generated at random then I'm not sure how it can grant those.
