### ISSUE TITLE
Concurrent builds using bundles can intermittently fail

### ISSUE THREAD

**Issue by or1can** [batect/batect#1409]
### Describe the bug

We're just starting to experiment with bundles, to share a common task across our terraform pipeline runs. Some stages of our terraform pipeline run concurrently.

We've observed an issue when concurrent jobs run, where one job will run while the other will fail. The job that fails will report an error like:

```
/some/path/to/batect.yml: Included file 'batect-bundle.yml' (batect-bundle.yml from git@github.com:my-bundle.git@main) does not exist.
```

It seems concurrent jobs will all attempt to fetch bundles, and then potentially attempt to use a bundle while it's being updated by another process.

### Reproduction repo

https://github.com/batect/bundle-dev-bundle

### Steps to reproduce

Run two or more `./batect --list-tasks` in concurrently.

### Expected behaviour

Both concurrent jobs will execute successfully.

### Actual behaviour

Some concurrent jobs will succeed and others will fail.

The reported error could be:

```
Cloning https://github.com/batect/hadolint-bundle.git 0.22.0...
/Users/Kevin/git/hmrc/bundle-dev-bundle/batect-bundle.yml: Could not load configuration file: /var/folders/nv/sjwm07qd4gs5pnm7fcngkq880000gn/T/batect-git-17163651371406863339 -> {$HOME}/.batect/incl/taLp7FfTD5MDdpQ2w55yKgmPDWoojyHcLA262w: Directory not empty
```

or

```
/some/path/to/batect.yml: Included file 'batect-bundle.yml' (batect-bundle.yml from git@github.com:my-bundle.git@main) does not exist.
```

### Version information

```plain text
Batect version:    0.83.0
Built:             2022-11-27 02:59:40 +0000
Built from commit: 0cba58813ad9bc2813c4bb7cb4eeae6d6edc083a (commit date: 2022-11-27 13:39:12 +1100)
JVM version:       Homebrew OpenJDK 64-Bit Server VM 18.0.2.1
OS version:        Mac OS X 13.0.1 x86_64
Docker version:    20.10.21 (API version: 1.41, minimum supported API version: 1.12, commit: 3056208, operating system: 'linux', architecture: 'amd64', experimental: false)
Git version:       2.37.1 (Apple Git-137.1)

For documentation and further information on Batect, visit https://github.com/batect/batect.
```

**Comment by charleskorn** [comment]
Thanks for the bug report @or1can. Were you seeing the same behaviour before v0.83? That version has a change that should fix this issue, so I'm surprised to see this, but there might be another problem at play.

**Comment by or1can** [comment]
Interesting, I'd helpfully ignored the message to update to version 0.83.0 😄

We encountered the issued using version 0.82.0, where a pipeline runs three jobs in parallel. We noticed that two of the jobs ran on the same server, and that one succeeded when the other failed.

The message with version 0.82.0 was:

```
/<batect project dir>/batect.yml: Included file 'batect-bundle.yml' (batect-bundle.yml from git@github.com:<repo>@main) does not exist.
```

We could replicate the issue locally by running `./batect --list-tasks` in two shells concurrently. After that initial failure, running the same command concurrently in two shells does not appear to cause an issue.

Upgrading to version 0.83.0 results in similar behaviour, but a different error:

```
<batect project dir>/batect.yml: Could not load configuration file: /var/folders/nv/sjwm07qd4gs5pnm7fcngkq880000gn/T/batect-git-11795258067651593642 -> /<my home dir>/.batect/incl/vMTiFc0QnrX9UkxOEk8k5VZrlDJuoo_fGpug9g: Directory not empty
```

Our hypothesis is this is an issue with the two concurrent invocations of batect trying to clone the bundle at the same time and clobbering each other somehow, rather than either of the clones explicitly failing - as we've only observed the failure with concurrent invocations.

**Comment by charleskorn** [comment]
> Our hypothesis is this is an issue with the two concurrent invocations of batect trying to clone the bundle at the same time and clobbering each other somehow, rather than either of the clones explicitly failing - as we've only observed the failure with concurrent invocations.

I think you're correct here. 

As a workaround, try running `./batect --list-tasks` before invoking any tasks - `--list-tasks` will download all bundles etc. first, and this should prevent conflicts from occurring.

**Comment by or1can** [comment]
The only workaround we've been happy with so far is to stop doing concurrent builds, and somewhat ironically, we started using batect to make concurrent builds safer 😄 

In that scenario, you can only run `./batect --list-tasks` from one job at a time. If both jobs try to run it concurrently, it would fail.

We don't necessarily know what job is going to run, so don't know what bundles batect needs to fetch.

That seems to leave us with a few options:

1. Only allow one job at a time on a server.
2. Add an initialisation step with some semaphore logic to our CI server. The initialisation step runs `--list-tasks` but ensures  only one can run at a time (something that behaves a little like a Java synchronised block, or similar).
3. Create a bootstrap project that has a `batect.yml` that includes all the required bundles that could be used by any job, and run `./batect --list-tasks` after boot so that all projects are up to date.

But none of these feels right, they all feel like workarounds, and leave me thinking batect is the right place to fix it, with some kind of locking (probably file based) - because the problem occurs when cloning a repo, does that mean it could happen when updating a repo as well?

Is there an expectation batect is safe to run concurrently (i.e. the same user running one task in two or more projects at the same time)?

**Comment by charleskorn** [comment]
Ah, I misunderstood your situation: I thought you were running different tasks from the same project at the same time, not different tasks from different projects. `./batect --list-tasks` as a workaround won't help then 🙂

You're correct, the real fix for this is for Batect to do some kind of locking to prevent simultaneous clones from conflicting with each other - the intention is that you should be able to run tasks from different projects concurrently safely. I'll take a look at adding locking shortly.
