### ISSUE TITLE
Mapping multiple host ports to single container port

### ISSUE THREAD

**Issue by MarwanAwroojXero** [batect/batect#1412]
### Describe the bug

I'm trying to do something like
container a:
  ports:
        - "11111:1433"
        - "11112:1433"
        - "11113:1433"

Which works fine on Docker compose, however batect seems to only pick the latest port mapping for one port.
This is usually useful when multiple services configured to use different ports for dependent service / database

### Steps to reproduce

create a container definition with multiple hosts ports mapped to a single container port

### Expected behaviour

container listen on all mapped host ports

### Actual behaviour

only last mapped port actually is configured in Docker

### Version information

```plain text
0.79.1 and I also tested on 0.83 and same thing
```

**Comment by charleskorn** [comment]
Hi @MarwanAwroojXero, thanks for the bug report.

To clarify: are you trying to access the same container's port from multiple ports on your local machine? Or would you like other containers running in the same task to be able to access the same container's port from different ports?

**Comment by charleskorn** [comment]
Resolved by #1420.
