### ISSUE TITLE
"Invalid cross-device link" error when attempting to list or run tasks

### ISSUE THREAD

**Issue by or1can** [batect/batect#1421]
### Describe the bug

We we're eagerly testing the fix for #1409 which looked good locally, but in our CI environment we immediately got the following error:

```
/<path to batect project>/batect.yml: Could not load configuration file: /tmp/batect-git-6442242487607141600 -> /<user home dir>/.batect/incl/vMTiFc0QnrX9UkxOEk8k5VZrlDJuoo_fGpug9g: Invalid cross-device link
script returned exit code 255
```

In our CI environment the /tmp folder is on the root volume, while the CI users home directory is on a separate volume. I think this triggers an issue with the fix for #1256 (the atomic move perhaps?)

### Reproduction repo

Any batect project that includes a bundle, where the project directory is on a different volume to the temporary folder.

### Steps to reproduce

Any batect project that includes a bundle, where the project directory is on a different volume to the temporary folder.

1. Run `./batect --list-tasks` or any other batect task.

### Expected behaviour

Batect should run without error if the default temporary directory is on a different volume to the batect configuration folder (`~/.batect`)

### Actual behaviour

Batect fails with a Java "Invalid cross-device link" error during the bundle clone phase, before tasks are listed, or run.

### Version information

```plain text
Batect version:    0.83.1
Built:             2022-12-18 04:02:01 +0000
Built from commit: 132f06fd12cd0ea2d84fc494d8db3a0b84056509 (commit date: 2022-12-18 14:40:02 +1100)
JVM version:       Ubuntu OpenJDK 64-Bit Server VM 11.0.17
OS version:        Linux 5.4.0-1092-aws amd64 (Ubuntu 18.04.6 LTS (bionic))
Docker version:    20.10.22 (API version: 1.41, minimum supported API version: 1.12, commit: 42c8b31, operating system: 'linux', architecture: 'amd64', experimental: false)
Git version:       2.17.1
```

### Any other information

Fiddling with the `batect` bash script in a crude way to make the temporary directory ~/.batect/tmp does allow batect to run tasks successfully.

[BAU_Test_batect_atomic_moves.patch](https://github.com/batect/batect/files/10276511/BAU_Test_batect_atomic_moves.patch)

**Comment by charleskorn** [comment]
Sorry about that @or1can - this should be fixed in 0.83.2, which I'll release shortly.
