### ISSUE TITLE
"Fake" a proxy environment

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1464]
### Describe the problem you'd like to solve

I'd like to ensure that the tests I'm running pass when run from a machine that can reach the Internet only via proxy.

### Describe the solution you'd like

It would be nice if there was an easy way for Batect to block all Internet traffic from the container, *unless* it's going via a configurable "fake" proxy.

### Additional context

I'm uncertain whether this is in-scope for Batect, and / or what means Docker might already provide to accomplish something like this. Also, this issue is distinct from #10.

**Comment by charleskorn** [comment]
Thanks for the suggestion @sschuberth. 

> I'm uncertain whether this is in-scope for Batect

I'd say this is out of scope for Batect, this seems like a fairly specific use case. 

> what means Docker might already provide to accomplish something like this.

I'm not aware of anything in Docker that will block or proxy traffic as you describe. However, if all you want to proxy is HTTP traffic, you could spin up a HTTP proxy as part of your Batect setup and set the appropriate environment variables (eg. `HTTP_PROXY`) on the other containers to forward traffic through the proxy.

**Comment by sschuberth** [comment]
> However, if all you want to proxy is HTTP traffic

I actually also went to ensure that traffic not going through the proxy would not work, to discover code that is not proxy-aware (and thus fails in such a setup).

> I'd say this is out of scope for Batect, this seems like a fairly specific use case.

Fair enough, I'll close this then.
