### ISSUE TITLE
Release 0.83.5 is missing assets, making RenovateBot fail

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1473]
### Describe the bug

The wrapper scripts are not published as assets at https://github.com/batect/batect/releases/tag/0.83.5.

### Reproduction repo

See https://github.com/oss-review-toolkit/ort/pull/6588.

### Steps to reproduce

$ ./batect --upgrade
Downloading latest update information...
The current version of Batect (0.83.4) is already up to date.

### Expected behaviour

The upgrade to release 0.83.5 should work.

### Actual behaviour

The upgrade to release 0.83.5 does not work.

### Version information

```plain text
$ ./batect --version
Batect version:    0.83.4
Built:             2023-01-29 10:56:03 +0000
Built from commit: 87143d15413a6fe93fe5f2f4887da20f726b249f (commit date: 2023-01-29 21:18:22 +1100)
JVM version:       Eclipse Adoptium OpenJDK 64-Bit Server VM 17.0.5
OS version:        Windows 11 10.0 amd64
Docker version:    20.10.22 (API version: 1.41, minimum supported API version: 1.12, commit: 42c8b31, operating system: 'linux', architecture: 'amd64', experimental: false)
Git version:       2.39.2.windows.1
```

**Comment by charleskorn** [comment]
Thanks for letting me know @sschuberth. I've fixed the issue and the binaries should be published once [this build](https://github.com/batect/batect/actions/runs/4307970738) completes.

**Comment by charleskorn** [comment]
If you're running Batect from the PR you linked to earlier, this is expected: Renovate wasn't able to update the wrapper script with the checksum, so the wrapper script still has the checksum from the previous version. 

You could wait until Renovate updates it automatically next time it runs, or alternatively update the scripts yourself by downloading them from the release page.
