### ISSUE TITLE
Support running multiple task with one CLI call

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1479]
### Describe the problem you'd like to solve

I have two independent tasks that I'd like to run consecutively, with a single invocation of Batect (for convenience).

### Describe the solution you'd like

It would be great if Batect (like e.g. Gradle) would support this by simply executing it like `./batect taskA taskB`.

### Describe alternatives you've considered

Running Batect twice (once per task) obviously works, but is inconvenient.

**Comment by charleskorn** [comment]
Thanks for the suggestion @sschuberth. Unfortunately this would make things tricky with Batect's support for passing arguments to tasks with `./batect taskA -- --another-arg`, and given it's not difficult to run multiple tasks with any shell that supports `&&` (eg. `./batect taskA && ./batect taskB`), I'm not sure this is worth the additional complexity.

**Comment by sschuberth** [comment]
> Unfortunately this would make things tricky with Batect's support for passing arguments to tasks with `./batect taskA -- --another-arg`

I was giving this some thought as well, and was hoping we could pragmatically support passing arguments only for the last task.

> it's not difficult to run multiple tasks with any shell that supports `&&` (eg. `./batect taskA && ./batect taskB`)

Things get a bit more nasty if setting of environment / config variables is involved like [here](https://github.com/oss-review-toolkit/ort/blob/eec3223e68525d32432c904d09cd7ef760bbb14d/.github/workflows/build-and-test.yml#L158-L162), you'd then need to repeat all of that.

**Comment by charleskorn** [comment]
> Things get a bit more nasty if setting of environment / config variables is involved like [here](https://github.com/oss-review-toolkit/ort/blob/eec3223e68525d32432c904d09cd7ef760bbb14d/.github/workflows/build-and-test.yml#L158-L162), you'd then need to repeat all of that.

Have you considered using a config variables file with `--config-vars-file` to simplify things? That might help reduce the duplication.

**Comment by sschuberth** [comment]
> Have you considered using a config variables file with `--config-vars-file` to simplify things?

No, but thanks anyway for the hint. But still things like `BATECT_QUIET_DOWNLOAD=true` and `--enable-buildkit` would need to be repeated, so it's not really of much help in this case.

**Comment by charleskorn** [comment]
Both of those could be set as environment variables at the job or workflow level (`--enable-buildkit` can be set with `DOCKER_BUILDKIT=1`).

Take a look at https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env for how to do this.
