### ISSUE TITLE
Add an option to just build the images needed for given tasks

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1510]
### Describe the problem you'd like to solve

I'd like to get a better understanding of the time spend by the (implicit) build of images vs. the time to actually execute the tasks in a container.

### Describe the solution you'd like

One way to get more insights could be to introduce an option to just build the images that are needed to execute the given task, but not actually execute the task inside the container. It's a bit like a "dry run", except that it would really do nothing, as still images would be built if not yet cached.

### Describe alternatives you've considered

To my understanding Batect would benefit from cached images / layers built by Docker CLI on the same host. So I could probably also run `docker build` manually once before to get the image build time, and then run Batect, which should not rebuild the image and thus the time spent is more or less just the execution time of the task.

However, it's more convenient to only have to deal with Batect, and to have Batect figure out what image needs to be built by looking at the task dependencies.

**Comment by charleskorn** [comment]
Thanks for the suggestion @sschuberth. 

I don't have time to work on this myself at the moment, but I'm open to a PR to add this. 

There are two things that would need to change I think:

- the execution plan would need to be modified to only include building and pulling images
- the default output formatter might need some modifications to account for only building and pulling images (it assumes that the container would be created after the image is built or pulled)
