### ISSUE TITLE
Version 0.83+ Fails on Amazon Linux 2 due to incompatible version of GLIBC

### ISSUE THREAD

**Issue by srisudarsan** [batect/batect#1538]
### Describe the bug

With a recent upgrade to dependency of jnr-posix in commit https://github.com/batect/batect/commit/6e12acc4537a39317364e100fe140e8e4731037a  has left batect failing from versions 0.83 on Amazon Linux 2

Amazon linux 2 only supports glibc version 2.26 and latest version of jnr-posix released with its jnr-ffi dependency which transitively uses jnr-jffi 1.3.10 is breaking on machines which has glibc older than 2.27

jnr-jffi has released a new version 1.3.11 which has fix the issue and has brought back support for older glibc versions - https://github.com/jnr/jffi/issues/138

Though, the latest version of jnr-ffi has not been released bundling the latest version of jnr-jffi

Until this is released, can we revert to use older version on jnr-posix (3.1.15) which could let us continue to use latest versions of batect on amazon linux 2 machines with glibc version 2.26 ? 

### Steps to reproduce

Spin up an ec2 instance with amazon linux 2
Try running batect command on that machine, 
we will get an error stating that glibc_2.27 is not found

### Expected behaviour

batect to run normally without any errors

### Actual behaviour

error - unable to find glibc_2.27

### Version information

```plain text
0.83 onwards
```

**Comment by charleskorn** [comment]
Thanks for the bug report @srisudarsan. I'm about to release 0.83.8 that should fix this issue.
