### ISSUE TITLE
Quoted shell-evaluated commands don't accept additional arguments

### ISSUE THREAD

**Issue by Tzrlk** [batect/batect#271]
From what I've read in the documentation, tasks can be executed with additional arguments passed to the specified command like so: `batect my-task -- arg1 arg2`. Also, when attempting to use shell interpolation in the command, it is required to modify the entrypoint to be something like `/bin/bash -c`, necessitating the command be quoted.

Unfortunately, because the command is considered a single unit, passing additional arguments to the task doesn't add them on the inside. Instead of `my command` being executed as `/bin/bash -c "my command arg1 arg2"`, it gets executed as `/bin/bash -c "my command" arg1 arg2`.

Some fiddling around shows that this can be worked-around by specifying the command as `"my command ${*}" --`. Though adding this to all commands that require any kind of interpolation seems like it could be standardised with an option of some description.

**Comment by charleskorn** [comment]
Hi @Tzrlk, thanks for the suggestion and apologies for the slow response. That's an interesting idea, I'll add it to the long list of ideas to take a look at in the future.

One other thing you might want to consider doing is creating a shell script of your own that accepts the extra arguments and passes them to the command correctly. It's a bit fiddly, but might be clearer than adding `${*}` everywhere.
