### ISSUE TITLE
docker --env-file option

### ISSUE THREAD

**Issue by yoyo-i3** [batect/batect#407]
Using batect has been super useful for me and my team; The one option that will be beneficial to running our containers would be the docker --env-file option as we have 100+ environment variables so we have an env.list file for each environment with its value and with docker we just use the --env-file option. It would be great to have this option in batect so we can pass the file name and location maybe for each of the containers.
Thanks

**Comment by charleskorn** [comment]
Hi @yoyo-i3, glad to hear you've found batect useful. 

Can I clarify where you'd like to use this environment file? Is it to pass options to containers for different environments? If so, you might be able to achieve the same thing with config variables (https://batect.dev/config/ConfigVariables.html). These give slightly better discoverability than environment variables and can also make it easier to reduce documentation. 

If that's not the use case you're working with, could you please help me understand with an example?

**Comment by yoyo-i3** [comment]
ConfigVariables are really useful, just started using them today for common variables shared between different applications. 
The need for environment files in our project is mainly because we want to have consistent way of deployment to the cloud and on premises environments.

For every environment we already have files with environment keys and their values; so we will have environment file for app1, different file for app2 and so forth. When using the docker run —env-file option we pass the file name which os the same way we use on cloud formation to deploy to the cloud.

Batect script already have all of the apps and the common env variables used for all of the apps (15+) along with their tasks which has already made the script too long and adding an extra line for the env-file for each container (app) will make it tidy and shorter than adding the different 100+ env variables for each of the containers along with adding their config_variables list.

I hope that made it a bit clearer..let me know if you’d like me to add any examples.
Thanks

**Comment by charleskorn** [comment]
Sorry, three more questions :)

* Are you asking for a command line option to pass a file containing environment variables to a container (something like `./batect --env-from=...`), or a way to reference this file from a container's definition in the batect config file?

* Are you sharing the environment variable files with other tools, or is the file used with batect only used when running and testing your app with batect? 

* Is the main concern with putting the values in config variables or just directly in the config file the size of the config file? If so, would something like #410 make this more manageable?

**Comment by yoyo-i3** [comment]
The config variables functionality is already working great so I was thinking just adding a script in the code or something to handle the config_variables option without having to add the actual variables in the batect.yml file at all.

Example:
batect.yml
—————
containers:
  app1:
    image: my-app:1.2.3
    environment:
         env_var1: env_var1_value
         env_var2: <env_var2_key
         config_vars_file: batect.local.yml
...
...
config_variables:
     env_var2_key:
         default: env_var2_default_value
....
....

batect.local.yml
———————-
enc_var2_key: env_var2_file_value
env_var3: env_var3_value
env_var4: .....
...
...
And once config_vars_file is passed to batect in the yaml file or in the command  —config-vars-file , all the list of key: value variables inside the file are set up in the container as environment variables so for every environment we can use a different file that has the relevant environment values without having to include the list again under the environment: option and config_variables: 

So static environment variables that will be different per app/container but same across all environments can be passed under the environment: option and can still use the config_variables: to have default values and read from the external file and the other dynamic ones can just be part of the external file and will still get the rest of the variables from the file set up as environment variables in the container as well.


I think that can probably feed into #410 as well so it will cut down the batect file size.

Let me know if that answers your questions..
And the our config files will be used by tools other than batect yes and the config-vars-file formatting is the same format this is why leveraging its use across all tools would be perfect!

Thanks a lot for the quick response.

**Comment by charleskorn** [comment]
Ok, so it sounds like you don't need anything extra in batect? Or am I misunderstanding?

**Comment by yoyo-i3** [comment]
The only two things that would be beneficial is having the below;

Can we use the config-vars-file option without having to add the variables in the config_variables list and in the container’s environment list?

And can we use multiple config-vars-file; one for each of the containers? so we can pass the config-vars-file name in the environment list for each container

Does that make sense?

**Comment by heyheman11** [comment]
Hi charles, I also have a similar request. It would be extremely helpful if batect had the ability to consume a .env file similar to how docker-compose consumes it, like [this](https://docs.docker.com/compose/compose-file/#env_file).

**Comment by charleskorn** [comment]
@yoyo-i3:

> Can we use the config-vars-file option without having to add the variables in the config_variables list and in the container’s environment list?

This is something I don't plan to add sorry - requiring config vars to be explicitly defined is one of the key benefits over environment variables (as it allows them to be validated and documented), and requiring them to be listed for containers prevents unintended side effects when you add or remove them. 

> And can we use multiple config-vars-file; one for each of the containers? so we can pass the config-vars-file name in the environment list for each container

This is definitely something I could see being added, but perhaps in a slightly different way - I'm imagining being able to pass `--config-vars-file` multiple times. Config variables are intentionally project-scoped (not set at a container level) as a common use case is sharing the same value between multiple containers, so I'm not keen to add the ability to set a config variable on a container level. If you're keen for this functionality, PRs are always welcome and will get the feature in sooner, otherwise this will go on my backlog to get implemented at some point :)

@heyheman11:

> It would be extremely helpful if batect had the ability to consume a .env file similar to how docker-compose consumes it, like this.

This (`env_file` property for containers) is something I could see being added. Again, if you're keen for this functionality, PRs are always welcome and will get the feature in sooner :)

**Comment by yoyo-i3** [comment]
Hi Charles,
I will have a go at it and if it worked for me, will do a PR for you to review. Thanks a lot for all the great work..

**Comment by charleskorn** [comment]
That would be great, thanks @yoyo-i3. If you'd like to get early feedback on a work in progress, I'm always happy to take a look.
