### ISSUE TITLE
batect.d folder to store batect files configuration instead of everything in batect.yaml

### ISSUE THREAD

**Issue by paulvalla-zorro** [batect/batect#410]
Hi, 

Our `batect.yaml` file is getting bigger and bigger, it would be great to have something to break this file into multiple configuration file, something like that:

```
batect.yaml:
  include: 
    - batect.d/batect_windows.yaml
    - batect.d/batect_linux.yaml
    - batect.d/batect-*.yaml
```

**Comment by charleskorn** [comment]
Makes sense to me, thanks for the suggestion @paulvalla-zorro!
