### ISSUE TITLE
additional hostname feature might not work under this windows environment

### ISSUE THREAD

**Issue by BethanyDrake-x** [batect/batect#412]
```
  batect version:    0.45
  JVM version:       Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 1.8.0_241
  OS version:        Windows Server 2019 10.0 (amd64)
  Docker version:    19.3.5 (API version: 1.40, minimum supported API version: 1.24, commit: 2ee0c57608, operating system: 'windows')
```

We are running windows container using batect, the `additional_hostnames` doesn't work when connecting from Container A to Container B using the additional hostname.

**Comment by BethanyDrake-x** [comment]
```
batect version:    0.45
Built:             2020-02-20 09:35:13 +0000
Built from commit: c4ec395d4ee7de05902343f386c97e73fe073518 (commit date: 2020-02-20 19:40:27 +1100)
JVM version:       AdoptOpenJDK OpenJDK 64-Bit Server VM 13.0.2
OS version:        Windows Server 2019 10.0 (amd64)
Docker version:    18.9.4 (API version: 1.39, minimum supported API version: 1.24, commit: c3516c43ef, operating system: 'windo
ws')
```

And it works using this set of versions.

**Comment by charleskorn** [comment]
Thanks for the bug report @BethanyDrake-x! Could you please try running the following commands on the affected machine and share the output with me?

```
docker version
docker network create --driver nat test
docker run --rm -it --network=test --network-alias=testalias mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 nslookup testalias
docker network rm test
```

Also, what image are you using?

**Comment by BethanyDrake-x** [comment]
docker version

Client: Docker Engine - Enterprise
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        c3516c43ef
 Built:             03/27/2019 18:22:15
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       c3516c43ef
  Built:            03/27/2019 18:20:29
  OS/Arch:          windows/amd64
  Experimental:     false


docker network create --driver nat test

0a66923392106f1cc8fd67796f6c0756565b3f1d6ea86931422a62c62192e751

docker run --rm -it --network=test --network-alias=testalias mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 nslookup testalias

Server:  UnKnown
Address:  172.31.240.1

Non-authoritative answer:
Name:    testalias
Address:  172.31.243.203

docker network rm test

test

**Comment by charleskorn** [comment]
Thanks for the info @BethanyDrake-x, I'll take a look.

**Comment by charleskorn** [comment]
I'm not able to reproduce this issue @BethanyDrake-x - what error message do you get when using `additional_hostnames`?

Also, are you able to share a sample configuration file that reliably shows this issue?

**Comment by charleskorn** [comment]
I'm going to go ahead and close this issue due to inactivity - if you have more information to share, please go ahead and reopen it.
