### ISSUE TITLE
Add capability to expose a range of ports

### ISSUE THREAD

**Issue by GerardWorks** [batect/batect#414]
A docker image for example 'Localstack' exposes a range of ports, as a batect user I would like to be able to expose a range of ports

for example:
docker compose file will have:
ports:
      - "4567-4599:4567-4599"

batect could have:
ports:
      - local: 4567-4599
        container: 4567-4599

**Comment by charleskorn** [comment]
Hey @GerardWorks, thanks for the suggestion. I'll add it to my backlog.

**Comment by charleskorn** [comment]
I've just implemented this and it will be part of the next release. Thanks again for the suggestion @GerardWorks!
