### ISSUE TITLE
Add support for bash task completion

### ISSUE THREAD

**Issue by wilvk** [batect/batect#466]
It would be great to have the ability to type the start of a task to run for a `batect.yaml` file and have bash complete the task name .

e.g.

If we have a task called `run-tests`

```bash
./batect -f ./tests/batect.yaml r<tab>
```

could autocomplete on tab to:

```bash
./batect -f ./tests/batect.yaml run-tests
```

**Comment by charleskorn** [comment]
Hey @wilvk, thanks for the suggestion! This has been on my roadmap for a while and I'm already tracking this with #116, so I'm going to close this as a duplicate.

**Comment by wilvk** [comment]
Ah, my bad. Didn't see it there! Thanks Charles.
