### ISSUE TITLE
[security] During build, some files become owned by root

### ISSUE THREAD

**Issue by binkley** [batect/batect#476]
This may be a "how Docker works" question.  However, if there is something Batect can do to help, I'd like to discuss.

----

Violating the principle of least astonishment, without use of `sudo`, a build creates `./docs/build` and everything underneath owned by `root`.  To wit:
```
$ find -user root | wc -l
94
```
The full output of `find` (without counting files) begins at `./docs/build`.  This causes `./gradlew clean` to fail, and resorting to `sudo rm -rf`.

The best I can guess (I'm still debugging): `docs/build.sh` calls `mkdocs` from within a Dockerized build; running as `root` _inside_ the container, and writing to `docs/build` as a mount.

What surprises me ... the ownership by `root` is leaking out.  My Docker know-how is mediocre; I would have expected a mapping from `root` to `$USER` for file ownership.

Is this expected?

----

Build output:
```
$ ./gradlew build

> Configure project :
Reckoned version: 0.52.0-dev.0.30+20200417T115057Z

> Task :app:test

UnixSocketFactorySpec > throws an appropriate exception when using non-primitive values STANDARD_ERROR
    Exception in thread "createSocketServer" java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
        at batect.os.unix.unixsockets.UnixSocketFactorySpecKt$createSocketServer$2.invoke(UnixSocketFactorySpec.kt:150)

UnixSocketFactorySpec > throws an appropriate exception when using primitive values STANDARD_ERROR
        at batect.os.unix.unixsockets.UnixSocketFactorySpecKt$createSocketServer$2.invoke(UnixSocketFactorySpec.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

> Task :docs:buildDocs
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /docs/build/docs 

BUILD SUCCESSFUL in 1m 16s
33 actionable tasks: 33 executed
```

**Comment by charleskorn** [comment]
Hey @binkley, yep, that's the expected behaviour. Have you had a look at https://batect.dev/tips/BuildArtifactsOwnedByRoot.html? It has a more detailed explanation of what's going on and how batect can help solve it.

**Comment by binkley** [comment]
Oh, hey, thanks!  No ... I missed that document.  I searched GitHub issues, but forgot about the wiki, etc.  Thanks!
