### ISSUE TITLE
Add support to join an existing docker network

### ISSUE THREAD

**Issue by hussein-joe** [batect/batect#509]
**_The problem_**
I am using Batect in my current project and I wanted my Batect services to connect to a Kafka cluster(with all Confluent platform services like connect, and control centre). I found that it is challenging to have a compose file with all Confluent services separate from the Batect file.
The only option I had was to copy all Confluent services to another Batect file and include it in the main one. But then I had to do some modifications and remove unsupported docker options like _tty_ from my services.

**_Possible solution_**
I check the code and found that you are creating a network with a random UUID, I was thinking if there is an option where I can specify a network ID. This way users can pre-create a docker network and use this network in Batect and the cluster's compose file.
As a result, all services in Batect would use the container names to access the containers in the compose file.

**_Benefits_**

- It might be faster to keep a big cluster like Kafka up and running in the background while doing normal work with Batect to test my application code without a need to keep bringing down and up Kafka cluster every time.
- No need to wait for all Kafka containers to be up and running to run my application task that is defined in the Batect file. 
- It might be easier to provision the cluster externally using bash scripts for example. One of the use cases I can think of is creating Kafka connectors to ingest data into Kafka cluster. Otherwise, I might need to run all these provisioning scripts everytime I bring up the Batect services.

**Comment by charleskorn** [comment]
Thanks for the suggestion @hussein-joe, I'll take a look.

**Comment by askfor** [comment]
It would be nice if Batect can run a compose file directly, there are many services (and 3rd party projects) already have a compose file.

**Comment by charleskorn** [comment]
@askfor, have you seen [Batectify](https://batectify.enchanting.dev/) by @ineffyble? It converts Docker Compose config files to batect format for you automatically.

**Comment by askfor** [comment]
Hi @charleskorn, I've seen that, but I think it's better to support docker-compose directly.
1. User or 3rd party project can still change the existing docker-compose file without effecting Batect. 
2. Sometimes it is desirable to separate the project's own container from dependencies, especially some complicated ones.  not sure if this can be addressed by "include", but still use docker-compose it much easier than using Batectify and then modify them manually.

**Comment by charleskorn** [comment]
It's an interesting idea - thanks for the suggestion @askfor! I'll keep it in the back of my mind for the future, but I'm not sure this would be high on my list of priorities.
