### ISSUE TITLE
Example of using batect with Buildkite

### ISSUE THREAD

**Issue by squirmy** [batect/batect#512]
When using Buildkite with command eval disabled it is not possible to pass the task as a command line parameter.

https://buildkite.com/docs/agent/v2/securing#disabling-command-eval
> Once disabled your build steps will need to be checked into your repository as scripts, and the only way to pass arguments is via environment variables.

This can be worked around be providing a wrapper script around batect, but would be nicer if it had native support in batect.

**Comment by charleskorn** [comment]
Hey @squirmy, thanks for the suggestion. How do you imagine this working? Something like setting `BATECT_TASK=the-task`, then running `./batect`?

**Comment by squirmy** [comment]
Yeah, thats exactly the environment variable I'm setting now and forwarding on to batect in a wrapper script.

Though thinking more after I made the suggestion, you may want to be able to include more args than just the task.

A BATECT_ARGS as a catch all for all arguments may work better. We could keep it simple, if no arguments provided on the command line check to see if BATECT_ARGS exists and use it if it does. No need to merge command line args and the environment variable.

What do you think?

**Comment by charleskorn** [comment]
I'm keen to keep the core CLI and wrapper script as focused and simple as possible, so I'm not sure I'd want to add this to the main application, and would instead suggest that functionality is implemented as a separate script that then calls `./batect`.

I'd be happy to add a page to the docs with an example script for Buildkite (similar to the pages we already have for [CircleCI](https://batect.dev/tools/CircleCI.html), [GitHub Actions](https://batect.dev/tools/GitHubActions.html) and [Travis CI](https://batect.dev/tools/TravisCI.html)) - how does that sound?

**Comment by squirmy** [comment]
Sure, sounds good. This is a particular use case for buildkite, and only is required if this option is set.

Looking at those pages they also go into some detail on the default agents / which images to use with batect. Build kite does have a list of default stacks, though its not obvious if it comes with docker and Java.

https://buildkite.com/docs/agent/v3

**Comment by charleskorn** [comment]
> Build kite does have a list of default stacks, though its not obvious if it comes with docker and Java.

Do you know which ones come with Docker and Java?

**Comment by charleskorn** [comment]
Hey @squirmy, I've had a go at adding some documentation for using batect with Buildkite in 29555db - would you mind taking a look and let me know if it looks reasonable? (I don't have access to a Buildkite instance of my own to test this on.)
