### ISSUE TITLE
Interactive tasks/guide for dealing with user input

### ISSUE THREAD

**Issue by priorax** [batect/batect#513]
At the moment, we have some tasks that are performed outside of batect due to the need to rely on user input, it would be nice to bring these into batect to standardise our processes into one tool.

Example:
 - Naming of a database migration

Current process for us:
  - Run through either a Powershell or a shell script (since our team work across both Windows and Linux) to create the migration with the user input for the name of the migration

Preferred process:
 - `./batect build-prod-migration`
   - If this was an interactive task, we would be able to prompt for user input for the name of the migration

Ideal scenario (unsure if passing args is supported, but I cannot see anything obvious)

 - `./batect build-prod-migration`
   - Shell script runs, verifies no args and prompts for name
 - `./batect build-prod-migration "some migration name here"`
   - Shell script runs, uses name passed through

I can understand this not being required for a build/test environment tool, but as a general go-script tool, it'd be a nice addition.

If there are any nice workarounds that solve the same problem I'm going for that doesn't lead to constant amending of the `batect.yml` file, that works too!

**Comment by charleskorn** [comment]
Hi @priorax, thanks for the question!

Both of the things you've mentioned should work fine - did you try one and it didn't work?

Prompting a user for input is supported - provided you're running batect in an interactive shell (eg. not on CI) and not using `--output=all`, it should work just like it does if you invoke the script directly and allow the user to enter input.

Passing extra args is also supported, the only thing you need to do is separate them from the task name with `--`, eg.  `./batect build-prod-migration -- "some migration name here"`

Side note: I'm interested in

> (unsure if passing args is supported, but I cannot see anything obvious)

This is supported and in the documentation, but I'm aware the documentation isn't great - to help me improve the docs (or help information built in to batect), could you tell me where you went to work out if this was supported?

**Comment by charleskorn** [comment]
Just wanted to follow up on this @priorax - did you have any further questions about this? If not, would you mind closing this issue?

**Comment by priorax** [comment]
Sorry for the delay!

More than happy for you to close it, I was looking for "interactive", "terminal" and "tty" and just couldn't find anything obvious, but if it's a working use case, more than happy for it to be closed!
