### ISSUE TITLE
Provide api for java?

### ISSUE THREAD

**Issue by askfor** [batect/batect#519]
Hi, is it possible to use batect in jvm? So it can be run in an integration test, kinda like https://www.testcontainers.org

**Comment by charleskorn** [comment]
Hi @askfor, batect inverts the responsibilities compared to Testcontainers:

With Testcontainers, your test code is responsible for starting containers, waiting for them to become ready etc. and then starting the tests. 

With batect, batect is responsible for starting containers, waiting for them to become ready etc., and then starting the container that runs your tests. This makes your tests much simpler, means you can use whatever language you want for your tests (including Java), and makes it easier to run your tests or application against real versions of dependencies, as they are not tied to the container orchestration mechanism. 

You can see an example of how this works in [the Java sample project](https://github.com/batect/batect-sample-java).

**Comment by askfor** [comment]
Thanks, I got it. Then I've another question that I didn't find the answer in the document. 
Do these containers join the same network as docker-compose does, or it there any mechanism let these containers communicate (like https://www.testcontainers.org/features/networking/ )？
So we can run multiple batect tasks in CI at the same time without port conflict.

**Comment by charleskorn** [comment]
Each container in the same task joins the same network. Each task creates its own network automatically, so unless you expose ports on the host, tasks shouldn't conflict with each other.

There's also [an open feature request](https://github.com/batect/batect/issues/509) to be able to specify the network a task uses, which would be useful if you want to run two tasks on the same network.

**Comment by askfor** [comment]
Thanks for your clarification.
