### ISSUE TITLE
Comparison with Earthly ?

### ISSUE THREAD

**Issue by DiegoAlpizar** [batect/batect#553]
How does this compare to https://github.com/earthly/earthly ?

Maybe add it to https://batect.dev/Comparison.html ?

**Comment by charleskorn** [comment]
Hey @DiegoAlpizar, thanks for the suggestion. I haven't heard of Earthly but I'll take a look and update the docs.

**Comment by binkley** [comment]
I'd like to help on this issue.
As an experiment, I'm kicking the tires on Earthly for my Java build practices project:
https://github.com/binkley/modern-java-practices

First thing I notice right off the bat: Installation for Earthly is more complex than for Batect. Batect is self-installing without requiring modification to APT or other OS files; in this regard, Earthly is closer to a traditional binary package installation than is Batect, and is similar to Docker in this regard.

**Comment by binkley** [comment]
I believe this is the repo that I'd clone, and push a PR from?
https://github.com/batect/batect.dev

**Comment by charleskorn** [comment]
> I believe this is the repo that I'd clone, and push a PR from? https://github.com/batect/batect.dev

Yep, that's correct.

**Comment by binkley** [comment]
The Earthly GitHub actions were trivial to use. Most of my time was fiddling with naming of things to improve the display of my project Action pages. :)

**Comment by binkley** [comment]
Build timings are anomalous between Batect and Earthly. In all cases, it's a trivial project with clean builds for Gradle and Maven.

|| Env || Container || Tool || Wall time
| Local | Batect | Gradle | 32s
| Local | Earthly | Gradle | 7s
| Local | Batect | Maven | 43s
| Local | Earthly | Maven | 6s
| CI | Batect | Gradle | 2m23s
| CI | Earthly | Gradle | 4m28s
| CI | Batect | Maven | 2m25s
| CI | Earthly | Maven | 5m34s

I understand why CI may be slower: resources and sharing VMs, etc.
What I don't understand are the local results for Earthly. I believe there is heavy caching happening automatically that somehow undoes the "clean" part of the build.

**Comment by binkley** [comment]
Batect has a pull for this comparison. Looking for feedback & tone.

https://github.com/batect/batect.dev/pull/1301

**Comment by charleskorn** [comment]
Resolved with https://github.com/batect/batect.dev/pull/1301 (thanks @binkley!)
