### ISSUE TITLE
Add option to suppress prerequisite task execution

### ISSUE THREAD

**Issue by Tzrlk** [batect/batect#611]
In the task definition for my project, I have a set of commands that should ideally be run in order. linting should be run after rendering, deployment should only run after successfully linting. However, when orchestrating this in a CI environment such as Jenkins, I find that I want to use the process flow available there, while still preserving the default behaviour locally.

Can an option such as --no-prereqs be added to simply skip any prerequisite tasks defined?

**Comment by charleskorn** [comment]
Hey @Tzrlk, thanks for the suggestion. It's an interesting idea, I'll add it to my backlog. (PRs are always welcome too :) )

**Comment by charleskorn** [comment]
I've just implemented this and it will be in the next release (0.58). Thanks again for the suggestion @Tzrlk!
