### ISSUE TITLE
Set a name for batect created networks

### ISSUE THREAD

**Issue by dflook** [batect/batect#612]
It's difficult to identify networks created by batect.
When batect creates networks can it set a sensible name & label? Perhaps based on the `project_name`.

**Comment by charleskorn** [comment]
Hey @dflook, thanks for the suggestion. That makes a lot of sense to me - I'll add it to my backlog.

**Comment by charleskorn** [comment]
I've just implemented this and it will be in the next release (0.58). Thanks again for the suggestion @dflook!
