### ISSUE TITLE
Batect will try to download all the docker image versions when there is no image tag be specified

### ISSUE THREAD

**Issue by hongyuanlei** [batect/batect#614]
Here is a container config:
```
 yamllint:
    image: cytopia/yamllint
```

There is no tag of this image, then when you try to run this container, Batect will try to pull all the versions of this image. It would be better it can use the latest as the default tag.

**Comment by charleskorn** [comment]
Hey @hongyuanlei, thanks for the bug report, I'll take a look.

**Comment by charleskorn** [comment]
I can reproduce this issue (and it also affects `--override-image`). 

For the time being, please use a tag when specifying an image.

**Comment by hongyuanlei** [comment]
Thanks for your reply.

**Comment by charleskorn** [comment]
Thanks again for the bug report @hongyuanlei - I've just fixed this issue and it will be part of the next release.
