### ISSUE TITLE
Making ports configurable

### ISSUE THREAD

**Issue by catacgc** [batect/batect#637]
Binding a local port on the host is very useful. Unfortunately, this makes it problematic when running builds in parallel on a Jenkins host (two PR builds for example).

It will be very useful to make ports configurable.

**Comment by charleskorn** [comment]
Hi @catacgc, thanks for the feedback. Could you please clarify what you mean by 'configurable'? Are you imagining a CLI option or something like that?

**Comment by catacgc** [comment]
Yes, at first I was thinking that making config expressions work in ports declarations would be enough. But now I have second thoughts about it. Here's my build definition: 

```
    ports:
      - { local: 8000, container: 8000 }
      - { local: 8001, container: 8001 }
      - { local: 8082, container: 8082 }
      - { local: 5005, container: 5005 } # remote debug from IntelliJ
      - { local: 6300, container: 6300 } # jacoco coverage reports
```

One ideea was to allow things like:

```
    ports:
      - { local: 8000, container: "<{some-port-var}" }
```

But this has the downside that it breaks any yaml schema parsing.

Now I am thinking it's better to have an option to conditionally bind local ports via a config variable, as I don't think there are valid use-cases for this feature on a CI box.

**Comment by charleskorn** [comment]
What if, instead of a config variable, it was a CLI flag? So then locally you run `./batect my-task` as per usual, and on CI you run `./batect --disable-ports my-task`, and batect would effectively ignore `ports` altogether, preventing any conflicts.

**Comment by catacgc** [comment]
Yep, that would be perfect for this use-case

**Comment by catacgc** [comment]
By the way, I can contribute this as well. Doesn't seem to be such a big change
