### ISSUE TITLE
Running on Remote DOCKER_HOST

### ISSUE THREAD

**Issue by smozely** [batect/batect#654]
Hi there,

Just wondering if its expected that I should / shouldn't be able to run batect pointing to a remote docker host?

I've setup DOCKER_HOST to point to my docker server, and batect starts working, pulls the image and attempts to start ... but then I get an error.

Error: Could not run container node-build-env.
Starting container 'id' failed: error while creating mount source path '/Users/steve/src/web': mkdir /Users: read-only file system`

I'm using the `node-build-env` and it works fine if run locally ... just wondering if this type of setup "should" work?

**Comment by charleskorn** [comment]
Hey @smozely, thanks for the question. 

If you are using any features that rely on local resources (volume mounts is the biggest one), this won't work - Docker doesn't support mounting volumes from one machine to another.

In theory, if your containers have no dependency on local resources, it _should_ work. However, this hasn't been tested - what's the reason for wanting to run against a remote Docker host?

**Comment by smozely** [comment]
Hey @charleskorn cheers for the quick response ...

Yeah of course that makes sense about docker not handling mounting volumes like that.

... Ah the main reason was just me trying to use an old Mac Mini as a docker host, and let me offload some work from my underpowered laptop. So not an important use case :) Thanks for the response
