### ISSUE TITLE
Occasional SocketTimeoutException during CreateContainerStep

### ISSUE THREAD

**Issue by SongGithub** [batect/batect#663]
Please help to diagnose this issue. It happens intermittently. 

```
+ ./batect bar
Running bar...
Pulling foo-env:11.0.0...
Pulled foo-env:11.0.0.

Error: An unexpected exception occurred during execution.
During execution of step of kind 'CreateContainerStep': java.net.SocketTimeoutException: timeout
```

**Comment by charleskorn** [comment]
Hey @SongGithub, sorry about that. 

Could you share the output of `./batect --version` so I can see what batect, Docker and OS version you're using?

Also, does this happen with only one task or container, or any?

**Comment by SongGithub** [comment]
hi @charleskorn , 
- batect 0.56
- Docker v19.03
- OS: centos7

It happens on any task/container.

**Comment by SongGithub** [comment]
is there any flag to turn on verbose error logging, so that when I catch it next time, the error log would give more details about root cause.

**Comment by charleskorn** [comment]
Yep, you can run batect with `--log-file=some-log.json` to create a log file at `some-log.json`.

The timeout that error is referring to is currently set to 60 seconds, which should be plenty of time. If you create a container using the Docker CLI directly, how long does it take? (eg. run `time docker create foo-env:11.0.0`)

**Comment by SongGithub** [comment]
thank you for reply and I will add a logging flag to it. Hope to catch it in action next time.

**Comment by charleskorn** [comment]
I'm going to close this due to inactivity. If you're able to investigate further, please feel free to re-open the issue.
