### ISSUE TITLE
batect not propagating host's /etc/resolv.conf to containers

### ISSUE THREAD

**Issue by SongGithub** [batect/batect#665]
batect is not propagating host's /etc/resolv.conf to the container. As a result, the DNS resolution fails. The example using alpine image is shown below.

Note that on running the same container using docker, the name resolution succeeds.
Further, on mounting host's /etc/resolv.conf to the container in the batect container definition and login to the container, the DNS resolution succeeds.

## note 
this issue is duplicated issue to #296. 
batect version = 0.56.0 

## triage result

running same Docker image, on same Docker host instance, it works fine. But as soon as turning back to use Batect, it starts this problem

```
 docker run -it build-env:11.0.0 sh -c 'curl https://pypi.org'
HTTP/1.1 200 Connection established

HTTP/2 200
```

```
[ec2-user@ip-1-1-1-1 /]$ ./batect curl
Running curl...
Pulling build-env:11.0.0...
Pulled build-env:11.0.0.
Running curl https://pypi.org in build-env...
curl: (5) Could not resolve proxy: forwardproxy

Cleaning up...
nslookup finished with exit code 5 in 3.4s.
```  

also I have tried ` configuring --dns-search for your Docker daemon` as suggested in #296 , but issue remains.
```
sudo dockerd -H unix:///var/run/docker.sock --dns-search <domain name found in working /etc/resolv.conf on instance>
```

notice in dockerD log, there is an extra line comparing to logs when using DockerCli. 
```
INFO[2020-10-02T10:42:26.625586069+10:00] failed to read ipv6 net.ipv6.conf.<bridge>.accept_ra  bridge=br-07000cac651e syspath=/proc/sys/net/ipv6/conf/br-07000cac651e/accept_ra
```

**Comment by charleskorn** [comment]
Hi @SongGithub, thanks for the detailed issue report. Does the name resolve correctly if you use the full domain name? (eg. `forwardproxy.mycompany.com` instead of `forwardproxy`)

Also, as mentioned in #296, this may be because Docker does some unusual things with non-default networks. If you run the commands in https://github.com/batect/batect/issues/296#issuecomment-562799749, do you see the same behaviour?

**Comment by SongGithub** [comment]
Yes, it resolves fqdn correctly. Only issue is that it can’t resolve the short forwardproxy URL to the fqdn correctly.

**Comment by SongGithub** [comment]
I have tried to run commands in #296 . But It didn’t manage to reproduce the symptom as seen with Batect.

**Comment by charleskorn** [comment]
OK, that's strange, batect isn't doing anything special around this. Are you able to share the full contents of `/etc/resolv.conf` when you run the container with and without batect?

Also, what image are you using? Some versions of Alpine don't support the `search` option in `resolv.conf`, which is required to get the behaviour you're expecting, and later versions support this but have limitations ([this page](https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS) explains the limitations).

**Comment by SongGithub** [comment]
> OK, that's strange, batect isn't doing anything special around this. Are you able to share the full contents of `/etc/resolv.conf` from within the container when you run the container with and without batect?
> 
> Also, what image are you using? Some versions of Alpine don't support the `search` option in `resolv.conf`, which is required to get the behaviour you're expecting, and later versions support this but have limitations ([this page](https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS) explains the limitations).

I have been done triage tasks to rule out issue with 
- nginx.conf.
- particular Docker image.

**Comment by SongGithub** [comment]
anyway

```
; generated by /usr/sbin/dhclient-script
search fake-company.com.au
options timeout:2 attempts:2 rotate
nameserver <an internal IP address>

```

**Comment by charleskorn** [comment]
Thanks @SongGithub. Is `resolv.conf` from the container the same when you run it with the Docker CLI directly and with batect?

**Comment by SongGithub** [comment]
>  Is resolv.conf from the container the same when you run it with the Docker CLI directly and with batect?

yes it is.

**Comment by charleskorn** [comment]
OK, that `resolv.conf` looks correct, so it's not that.

I've tried to reproduce this problem myself in a similar environment but have not had any luck - are you able to share a `batect.yml` that exhibits this problem so I can reproduce it and debug it myself?

**Comment by charleskorn** [comment]
I'm going to close this due to inactivity. If you're able to investigate further, please feel free to re-open the issue.
