### ISSUE TITLE
Slow container start times with latest version of Docker for Mac (v2.4)

### ISSUE THREAD

**Issue by charleskorn** [batect/batect#679]
It seems the introduction of a new file sharing feature in the latest version of Docker for Mac can cause containers to take quite a long time to start (20-30s).

Symptom in batect is batect saying the container has started, but there is no output from the task for a while, or an error about a timeout during `RunContainerStep` or `InitialiseCachesStep`.

If this is happening to you, try disabling gRPC FUSE in Docker's Preferences window:

![image](https://user-images.githubusercontent.com/4017646/95644175-89848100-0b00-11eb-9d33-1de39cd01c1e.png)

**Comment by dalzymendoza** [comment]
Thanks, this solved my issue.
