### ISSUE TITLE
Gradle build best practices

### ISSUE THREAD

**Issue by binkley** [batect/batect#706]
Howdy @charleskorn!

I've been working at [a long-form article on "best Java/JVM build practices" for the local build](https://github.com/binkley/modern-java-practices) (my first 100+ star repo!).  I note you handle your Gradle build a little differently than the conclusions I came to.  For example, my suggestion is to fix plugin versions in `settings.gradle`.  And I see you deal with multi-module Gradle builds, which I avoided discussing.

If I may, I might suggest also fixing the versions of plugins in `settings.gradle`.  This lets one define all dependent versions in `gradle.properties` so they are all in one place: easily inspectable, and editable from a single file (which I take advantage of with of with Ben Manes' excellent "versions" plugin, to make it easy to spot out-of-date plugins/dependencies).  (**NB** -- I'm not suggesting your versions are out of date, only that it's hard to automate checking from the command line.)

I'd like to fork the Batect repo, and submit a PR to update the Gradle build along these lines.  **Thoughts, opinions?**

I'm also looking for your thoughts on working in a multi-module Gradle repo.  This is an area I'd like to discuss in my article, and share the hard-won knowledge of others.

Cheers

**Comment by binkley** [comment]
Actually, I full of puffy, powdery stuff.  I found Ben Mane's plugin in your `build.gradle`.  I don't know why I missed this on first pass!

**Comment by binkley** [comment]
OK, I'm doing the poor Netiquitte thing and reopening.  Would you be open to a "build" PR?

No code changes, just refreshing the build.

**Comment by charleskorn** [comment]
Hi @binkley, thanks for the offer of a PR. What did you have in mind for refreshing the build?

**Comment by binkley** [comment]
It's overall a solid build, so "refresh" is too strong a word.  More projects should show the respect for the local build that you do.

I'd like to:

1. Pull the version numbers out of the build, keeping them all one spot: `gradle.properties`
2. Convert to Kotlin build syntax (since this is a Kotlin project)
3. Possibly lock down `dependencyUpdates` to only use release versions (up to you)
4. Possibly add a few more "developer convenience" plugins (ex: the task tree plugin)

There are also some interesting things you do I'd like to explore on my own more:

* Breaking up the top-level `build.gradle` via `apply`: Nice technique
* Contrast with the more typical `include` in `settings.gradle` for a multi-project build
* Study how you are using dependabot -- I might steal this for my article on modern build practices :)

**Comment by charleskorn** [comment]
Those all sound like great ideas. I'd suggest submitting each of these as their own PR to keep the PRs small.

> 1. Pull the version numbers out of the build, keeping them all one spot: gradle.properties
> 2. Convert to Kotlin build syntax (since this is a Kotlin project)

This will almost certainly break Dependabot (it doesn't yet support Gradle configuration in Kotlin, and I don't believe it's sophisticated enough to understand variables), but I've been thinking about switching to Renovate anyway, which does support both of these. I'm happy to set up Renovate as a separate piece of work.

> 3. Possibly lock down dependencyUpdates to only use release versions (up to you)

Sounds like a good idea to me, I have a command in my shell history that sets dependencyUpdates to use release versions so if that can just be the default that would be great.

> 4. Possibly add a few more "developer convenience" plugins (ex: the task tree plugin)

Sure - which plugins did you have in mind?

> 5. Add optional use of the OWASP dependency check plugin -- shifting security left -- this is something CI can run

Sounds like a great idea, and would be awesome to get this running as part of CI as well.


I'm not sure what's going on with your local build - [line 15 of `Application.java`](https://github.com/batect/batect/blob/master/wrapper/testapp/src/main/java/testapp/Application.java#L15) should be entirely inoffensive, and doesn't contain a `\` character either... what happens if you remove Spotless?

**Comment by binkley** [comment]
Note a change I'm adding to my fork, in support of:

1. Consistency in `build.gradle`
2. Eventual PR for Kotlin-based DSL

I'm regularizing the quoting throughout `build.gradle`(s) to use double quote marks rather than single quote marks.  Groovy supports them both, whereas Kotlin supports only double quote marks.

I hope to get a PR out today (depending on time demands from my day job :) ).

Also, merge from upstream went poorly on my fork. :(  Git merge algos do poorly in general with single-character changes like this _vs_ whole-line changes.

**Comment by binkley** [comment]
re: Skipping Spotless

I'm working to move _all_ plugin, tooling, and dependency versions into root-level `gradle.properties`:

1. Avoid spreading version numbers across multiple `build.gradle` files
2. Make it clear in one place that plugin and tooling versions are often related

_However_, spotless `spotlessApply` task is **deleting** the `pluginsManagement` block from `settings.gradle`.  I'm researching/experimenting how to avoid this.

**Comment by charleskorn** [comment]
> _However_, `spotlessApply` task is **deleting** the `pluginsManagement` block from `settings.gradle`. I'm researching/experimenting how to avoid this. My local build passes with `./gradlew clean build -x spotlessGradleCheck`

Is the `pluginsManagement` block the first block in that file? Spotless does some weird stuff for Gradle scripts to determine where the license header should end up. It's based on a regex that finds the first non-license statement in the file, and is defined in https://github.com/batect/batect/blob/master/gradle/spotless.gradle#L50. It may be that we just need to add `pluginsManagement` as another option in that regex.

https://github.com/batect/batect/blob/1a4c8137efa00761321e166759c7d324f1f9d519/gradle/spotless.gradle#L50

**Comment by binkley** [comment]
The runtime syntax rules for `settings.gradle` require that the `projectManagement` come at the top.

Thanks for the pointer on the license text.  I'll experiment with that regex.
