### ISSUE TITLE
Local build on Linux creates docs/build as root-owned

### ISSUE THREAD

**Issue by binkley** [batect/batect#714]
This is something I'm researching.  I find that running:
```
$ ./gradlew clean build
```
results in `./docs/build` output directory as owned by "root", so a following `./gradlew clean` fails for permissions.

**To reproduce** (I'm using current Ubuntu 20.04 LTS):

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
$ ./gradlew clean build
# Output ommitted -- SUCCESS
$ ./gradlew clean
# Output truncated to here -- FAILURE
> Task :docs:clean FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs:clean'.
> java.io.IOException: Unable to delete directory '/home/binkley/src/batect/docs/build/docs'
# Further output ommitted
$ ls -ld docs/build
drwxr-xr-x 3 root root 4096 Nov  5 14:18 docs/build
```

**NOTE** CI builds would not catch this (I believe) as they always start "clean".

**Comment by charleskorn** [comment]
Ah good catch - that would be because the docs build is running from within a Docker container. 

I'm in the midst of completely revamping the docs (including moving them out of this repo), so fixing this is a low priority for me. For now, you could try disabling building the docs if this is impacting other things.

**Comment by binkley** [comment]
Understood.  It caught me off guard -- my "build practices" repo doesn't exhibit this behavior when I run Batect from command line.

Ah ... /light dawns/  <-- I see what happened: it's not running Batect, it's running through Docker.

**Comment by charleskorn** [comment]
With the move to the [new docs](https://github.com/batect/batect.dev) this should no longer be an issue. Thanks again for the feedback @binkley!
