### ISSUE TITLE
Introduce JaCoCo for local code coverage

### ISSUE THREAD

**Issue by binkley** [batect/batect#715]
**AS A** developer
**I WANT** my local build to fail when I drop coverage
**SO THAT** I have confidence in new or changed code

I noticed the CI build in GitHub relies on Codecov, and there is no matching equivalent in my local build (I see `~/.codecov.yml` in the root for the CI action to use).  I also don't know when I should crank up the the coverage number(s).

I'd like to introduce JaCoCo to the local build:

1. Know how my edits are changing coverage
2. Get a local HTML report I can review to find where coverage changed
3. (Optionally) fail my local build if I drop coverage too much
4. (Optionally) raise my minimum coverage as I improve the test coverage

I recognize that code coverage is a "passionate" issue for many.  Please treat this issue as a suggestion.  :)

**Comment by charleskorn** [comment]
Hey @binkley, this is available but disabled by default because I found it has a large (~50%) impact on build and test cycle times.

If you'd like to generate code coverage, run the build with `-PgenerateCoverage=true`, eg. `./gradlew check jacocoReport -PgenerateCoverage=true`.

**Comment by charleskorn** [comment]
(If there's a better way to do this, I'd love to hear it, this seems very awkward.)

**Comment by binkley** [comment]
Sounds good.  For me, I haven't found before that JaCoCo contributes must to overall build times (_vs_ PITest, for example, which clearly does), but I haven't tried many multi-project projects.

I'll close this for now, and do some before/after timing comparisons before submitting a PR to make coverage the default for local build.
