### ISSUE TITLE
Feature proposal: HCON as alternative to YAML

### ISSUE THREAD

**Issue by catacgc** [batect/batect#724]
[HOCON](https://github.com/lightbend/config/blob/master/HOCON.md) is a much more capable (and, subjectively, more readable) configuration lanaguage than YAML

Given that kotlin serialization supports it already, it would be a perfect fit for batect, with some built in capabilities that are very powerful:
- composability: the biggest thing I miss in batect right now. Example: ability to use a volume configuration for osx (with caches) and another one for a build system. 
- support for includes
- support for env variables
- support for optional overrides 

The real complexity comes from updating the docs, but maybe a section discussing HCON would suffice.

**Comment by charleskorn** [comment]
Hey @catacgc, thanks for the suggestion.

I'm interested to understand more about some of the ideas you raise there and how the existing YAML configuration file format isn't meeting your needs. Could you elaborate on how the existing format isn't working for you and how HOCON would work better? If you could provide some examples of what you're thinking, that would be even better.

**Comment by charleskorn** [comment]
I'm going to close this due to inactivity. If you're able to provide more information, please feel free to reopen this issue.
