### ISSUE TITLE
Can't start container if Unix group doesn't exist

### ISSUE THREAD

**Issue by jbduncan** [batect/batect#730]
I'm seeing a strange error when I run this example project, which I was hoping you could help me with: https://github.com/jbduncan/batect-failing-example.

When I manually start up a container based on the AdoptOpenJDK image in the project above, and then I access its shell with `docker exec -it <container-name> /bin/sh; exit`, it works fine for me. By comparison, when I run `./batect shell`, it prints an unexpected error.

I'm not familiar enough with Docker to know how to run the container in the same "run_as_current_user" mode that I've enabled in the above project's `batect.yml`, so I don't know if this is a bug with batect or AdoptOpenJDK.

### Reproduction instructions
1. `git clone https://github.com/jbduncan/batect-failing-example.git`
2. `./batect shell`

### Expected result
I see the shell of the container.

### Actual result
```
❯ ./batect shell
Running shell...
build-env: creating container...

Error: An unexpected exception occurred during execution.
During execution of step of kind 'CreateContainerStep': java.lang.RuntimeException: Group with GID 1687511723 does not exist.

Clean up: done

The task shell failed. See above for details.
```

**Comment by charleskorn** [comment]
Hey @jbduncan, thanks for the detailed issue and repro project. 

Could you please confirm a few details so that I can work out what's going on?

* What OS are you using on your machine?
* What's the output of running `id -g` and `id -gn` on your machine?

**Comment by jbduncan** [comment]
@charleskorn Wow, thanks for the quick response. :)

I'm using macOS Catalina 10.15.7 with Docker Desktop.

My outputs for the commands you requested are as follows:

`id -g`: 1687511723
`id -gn`: 1687511723

**Comment by charleskorn** [comment]
Looks like something weird has happened with your system's groups. `id -g` should give the ID of your primary group (norrmally `staff` on macOS), and `id -gn` should give the name of your primary group. The fact that `id -gn` is returning the ID suggests that something has gone awry.

If you go to Users and Groups in System Preferences, unlock it and then right-click on your user and select Advanced Options, what does it list in "Group"?

**Comment by jbduncan** [comment]
@charleskorn Ah, interesting.

It says "1687511723" for my group. My user ID is a different number, if that helps.

I wonder if my group is like that because my employer, who owns the MacBook, has done something unusual with the machine setup.

Any further thoughts on this? Is this something I should raise with my employer, or is it something that batect could work around?

**Comment by charleskorn** [comment]
Unfortunately it's not really something batect can easily work around - your user is in an invalid state. This might be because your employer has set your machine up like this, but the only other time I've seen something like this was when there was some file corruption going on (normally group IDs are somewhere between 2 and 5 digits).

The best thing to do would be to get your primary group set back to a group that actually exists. I'd suggest either resetting your user's group back to `staff`, or if that group ID is intentional, creating a group with that ID.

**Comment by jbduncan** [comment]
Hmm. A colleague of mine has done a quick search on the `id` man page, and he came up with this:

```
     -n      Display the name of the user or group ID for the -G, -g and -u options
             instead of the number.  If any of the ID numbers cannot be mapped into names,
             the number will be displayed as usual.
```

This kind of suggests to me that this behaviour, although very unusual, is not unexpected.

Any further thoughts on this?

**Comment by jbduncan** [comment]
@charleskorn FYI, I'm just checking if the result of `id -g(n)` is the same for all my colleagues or not.

**Comment by jbduncan** [comment]
Unfortunately, all my dev colleagues have the same group name and ID as me, and I've not yet heard anything from the team inside my company who looks after our Macs...

I acknowledge that this is a hairy situation and you're hesitant to move forward because batect can't easily work around this edge case, so if you'd find it helpful, I'd be more than happy to delve into the batect source code and see if I can raise a PR?

**Comment by jbduncan** [comment]
@charleskorn I have some good news, albeit some strange news.

Enabling my company VPN changes my machine's unix group name to something reasonable, apparently. I never knew VPN could do that! And batect doesn't choke on it, which is fantastic. ✨ 

I'd still like to investigate this further though, so if you're open to my suggestion in https://github.com/batect/batect/issues/730#issuecomment-731230945, I could see if I can fix the problem in batect more generally?

**Comment by charleskorn** [comment]
That is strange but good news :) It looks adding a workaround for this weird situation isn't too difficult (and wouldn't break anything that relies on the information), so I'll push up a fix for this shortly.

**Comment by jbduncan** [comment]
Wow! Thank you very much for implementing this workaround so quickly. (And also thank you for being so receptive in general!)

I'll use my VPN-based workaround for now, but I'm very much looking forward to the next release of batect. :)

**Comment by jbduncan** [comment]
Oh, I should've looked at the releases first. 😅

Thank you very much as well for the very fast bug-fix release! Looking forward to trying it out as soon as I have the opportunity.
