### ISSUE TITLE
docker rate limit for batect-cache-init-image

### ISSUE THREAD

**Issue by xdavidnguyen** [batect/batect#732]
hi,

we recently hit the docker rate limiting when running batect in CI: `Pulling the cache initialisation image 'batect/batect-cache-init-image@sha256:ac625b08d33aa6af8b0a5c61aa59e3c06d75007138b2e26d607c95274b2daed5' failed: Pulling image 'batect/batect-cache-init-image@sha256:ac625b08d33aa6af8b0a5c61aa59e3c06d75007138b2e26d607c95274b2daed5' failed: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

For other images, we can change to pull image through artifactory cache, but this image seems to be hardcoded here: https://github.com/batect/batect/blob/c16710cd19348bfd4bcbccd63d813daab691c8fa/app/src/main/kotlin/batect/execution/CacheInitialisationImage.kt#L20 

is there any workaround for this issue at the moment?

thanks

**Comment by charleskorn** [comment]
Hey @xdavidnguyen, thanks for reporting this issue, I'll see if there's anything I can do to prevent this. 

In the meantime, you can try pushing the image to a private image registry and then passing the image name to batect with [`--linux-cache-init-image`](https://batect.dev/CLIReference.html#set-cache-initialisation-image-linux-cache-init-image), or by setting the `BATECT_LINUX_CACHE_INIT_IMAGE` environment variable.

**Comment by charleskorn** [comment]
I've submitted a request to Docker to have that repository included in their Open Source program (which would remove the rate limits for everyone). If I don't get a response within a few days, I'll investigate moving the image elsewhere.

**Comment by xdavidnguyen** [comment]
thanks @charleskorn for the quick response

**Comment by xdavidnguyen** [comment]
hey @charleskorn , just thinking whether batect can provide an option to set the batect cache image at global level instead of having to provide either env variable or flag in every batect command that uses cache?

**Comment by charleskorn** [comment]
What did you have in mind @xdavidnguyen? A property in the configuration file or something else perhaps?

**Comment by xdavidnguyen** [comment]
yes, properly something like the built-in config var `project_name` where you have the option to override it like other config variables

but thinking from different perspective, batect cache image is internal to batect and users properly don't want to concern with what tag of that image to use either. So an option to specify docker remote server (default to docker hub) is better in my opinion

**Comment by charleskorn** [comment]
Just to keep you updated: Batect has been accepted into Docker's open source program, so the pull limits will be removed from the cache init image. This might take a day or two to take effect.

**Comment by charleskorn** [comment]
I've just been informed by Docker that the rate limits have been removed. If you're still encountering issues with this, please feel free to comment here.
