### ISSUE TITLE
Problem with search results on https://batect.dev/search

### ISSUE THREAD

**Issue by Abhisha1** [batect/batect#769]
Hi there! 

I've been using batect and was using the search functionality in the browser to investigate caching. I can see a view results when searching from the homepage, but when I click to view more results and get redirected to the search page, it yield no results (tried a bunch of terms to verify). I've attached a screenshot of the error below.

Thanks 
![image](https://user-images.githubusercontent.com/35671786/102947141-b7317180-4516-11eb-8e95-b052715ded01.png)

**Comment by charleskorn** [comment]
Thanks for letting me know about this @Abhisha1 - this is something I'm aware of and am looking into. Like you said, the quick search box does display results, so I'd suggest using that for now.

**Comment by charleskorn** [comment]
This should be fixed now, thanks again for your feedback @Abhisha1!
