### ISSUE TITLE
private registry support?

### ISSUE THREAD

**Issue by hpcsc** [batect/batect#789]
Hi,

I can't find any documentation regarding support for pulling images from private registry? Is that not supported at the moment?

More on my current project setup and problem: 

- CI server is Azure Devops.
- Before running batect command with private image, I already use Docker task to do login to registry: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops. From what I can see in the source code of this Docker task, it does the login and set the credentials in a temporary docker `config.json` file (`DOCKER_CONFIG` environment variable points to that location)
- If I use Azure Devops script task and run `docker run`, it's able to use `DOCKER_CONFIG` and pull private image fine
- batect doesn't seem to support `DOCKER_CONFIG` yet, can't read credentials to private registry and fails to pull the image

For a workaround, I need to do docker login, docker pull image before running batect command. It would be much nicer to have support for `DOCKER_CONFIG` or any other form of login to private registry

**Comment by charleskorn** [comment]
Hey @hpcsc, thanks for the detailed issue report. Batect does support pulling images from private registries, but relies on the credentials being configured in the default Docker configuration file (`~/.docker/config.json`). 

Adding support for the `DOCKER_CONFIG` environment variable shouldn't be too difficult though, I'll take a look at adding that.
