### ISSUE TITLE
Subsequent timeouts on macOS Docker after initial success

### ISSUE THREAD

**Issue by mjstrasser** [batect/batect#812]
I am getting repeated timeouts running Batect on macOS.

# Setup

* macOS Catalina 10.15.7
* Docker Desktop 3.1.0 (51484) including Engine 10.10.2
* Docker feature **Use gRPC FUSE for file sharing** is disabled
* Batect 0.68.0
* Project is [WireMock Async](https://github.com/mjstrasser/wiremock-async) (See [batect.yml](https://github.com/mjstrasser/wiremock-async/blob/main/batect.yml))

# Observations

* The first run of Batect went OK (see example below). Sometimes one or more following runs are also OK; sometimes not.
* Following runs fail with timeout (see example below).
* After restarting Docker, the next Batect run is fine but subsequent ones time out.

The problem appears to be with Docker volume mounting. I tried executing
```
$ docker run --rm -it -v $HOME/dev/wiremock-async:/code -v $HOME/.gradle:/root/.gradle -v $HOME/.m2:/root/.m2 adoptopenjdk:11-jdk-hotspot /bin/bash
```
when Docker was in the ‘stuck’ state but it never responded. After restarting Docker I could execute this command many times.

Is there an issue with Batect caching of volumes?

# Example output

## First run

All good, with output like:
```
$ ./batect build-gradle
Running build-gradle...
build-env: running ./gradlew --no-daemon clean build

<-------------> 0% INITIALIZING [531ms]
> Evaluating settings
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/container-user/.gradle/wrapper/dists/gradle-6.8.3-bin/7ykxq50lst7lb7wx1nijpicxn/gradle-6.8.3/lib/groovy-all-1.3-2.5.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass

BUILD SUCCESSFUL in 36s
7 actionable tasks: 6 executed, 1 up-to-date

build-gradle finished with exit code 0 in 39s.
```
(We can ignore the Gradle warning. It is not relevant).

## Subsequent runs

Wait a while then:
```
$  ./batect build-gradle
Running build-gradle...
build-env: running ./gradlew --no-daemon clean build


Error: An unexpected exception occurred during execution.
During execution of step of kind 'RunContainerStep': java.net.SocketTimeoutException: timeout

Clean up: done

The task build-gradle failed. See above for details.
```

**Comment by mjstrasser** [comment]
Some more information. 

* After I commented out `options: cached` for all the volumes in `batect.yml` I could run Batect repeatedly without problem.
* After I uncommented _one_ of the `options: cached` settings (for the local directory) I could run Batect once only. The second run timed out.

**Comment by charleskorn** [comment]
Hi @mjstrasser, thanks for the detailed issue. I'm not able to access your repo - is it private?

`options: cached` isn't a Batect feature - that enables Docker for Mac's [cached volume mode](https://www.docker.com/blog/user-guided-caching-in-docker-for-mac/). Unfortunately, it seems every new release of Docker for Mac introduces new and different issues with file sharing. 

I have seen this issue before with the original file sharing implementation - have you tried enabling gRPC FUSE for file sharing? I believe many of the issues in earlier versions have been fixed, and that it now has better performance than the original file sharing implementation.

Alternatively, if you see acceptable performance without `options: cached`, then leaving that out would also be an acceptable solution.

**Comment by mjstrasser** [comment]
Hi @charleskorn

Sorry about the private repo. I have made it public now. 

I ran some tests on another machine that almost the same, except that it is running macOS Big Sur 11.2.1. I found that that with Docker Desktop for Mac 3.1.0 requires **gRPC FUSE** to be enabled for repeated Batect runs to succeed.

I ran Batect multiple times in Zsh using:
```shell
for ((i = 0; i < 10; i++)); do time ( ./batect build-gradle; ); done
```
Before each run I re-started Docker.

* With **gRPC FUSE** disabled, I got 2 successful runs followed by 8 failures (twice).
* With **gRPC FUSE** enabled, I got 10 successful runs (twice).
* There was no significant difference in timing (reported by Gradle or `time`) between runs with `options: cached` and without.

**Comment by charleskorn** [comment]
OK, so it sounds like the issue is the original (non-gRPC) file sharing implementation in Docker for Mac. You should be able to reproduce the issue without Batect by appending `:cached` when creating volume mounts with `docker run`, for example:

```
docker run --rm -it -v $HOME/dev/wiremock-async:/code:cached -v $HOME/.gradle:/root/.gradle:cached -v $HOME/.m2:/root/.m2:cached adoptopenjdk:11-jdk-hotspot /bin/bash
```

If that exhibits the same behaviour when run multiple times in a row, this is definitely a bug in Docker for Mac - I'd suggest filing a bug with the Docker team to see if they can investigate further.

**Comment by mjstrasser** [comment]
Sorry if I wasn’t clear. The issue is not with Docker caching,
it is with the use of **gRPC FUSE**.

Timeouts happen after a couple of runs when **gRPC FUSE** is disabled
in Docker for Mac and `run_as_current_user` is enabled in Batect.

I ran the same Gradle command five times each in Docker a number of ways with these results:

| **gRPC FUSE** | Command | User | Result |
|--|--|--|--|
| disabled | `docker run` | root | success |
| enabled | `docker run` | root | success |
| disabled | Batect | root | success |
| enabled | Batect | root | success |
| disabled | Batect | non-root | **timeout failures after 2 runs** |
| enabled | Batect | non-root | success |

I timed all the runs and found that specifying `:cached` produces a
30–40% increase in speed, but only when **gRPC FUSE** is disabled.

**Comment by charleskorn** [comment]
Is there any noticeable speed difference between successful runs of these three scenarios?

| gRPC FUSE | Command | User |
|--|--|--|
| disabled | `docker run` | root | 
| disabled | Batect | root  |
| disabled | Batect | non-root | 

Also, are you able to capture logs for the failing scenario (eg. run with `./batect --log-file batect.log build-gradle`) and share the exception stack trace? (Search for `exception` in the log file to find the relevant line.)

**Comment by mjstrasser** [comment]
Here are average timings in seconds from 5 runs each a couple of days ago:

| **gRPC FUSE** | Command | User | Not cached | Cached | Notes |
|--|--|--|--|--|--|
| disabled | `docker run` | root | 40.9 | 28.1 | 
| disabled | Batect | root | 46.7 | 32.8 |
| disabled | Batect | non-root | 53.7 | 31.6 | 2 successful runs |

Timings reported by `time`.

**Comment by mjstrasser** [comment]
Every Batect timeout log includes an exception with this stack trace:
```
java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:146)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at batect.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:35)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at batect.docker.api.ContainersAPI.start(ContainersAPI.kt:112)
	at batect.docker.client.ContainersClient.run(ContainersClient.kt:68)
	at batect.execution.model.steps.runners.RunContainerStepRunner.run(RunContainerStepRunner.kt:39)
	at batect.execution.model.steps.TaskStepRunner.run(TaskStepRunner.kt:44)
	at batect.execution.ParallelExecutionManager$runStep$1.run(ParallelExecutionManager.kt:151)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mjstrasser** [comment]
# Docker for Mac updated to 3.2.0

After updating, I observed:

* The **gRPC FUSE** option is under **General** Preferences,  not **Experimental Features**.
* If **gRPC FUSE** is _disabled_, the same timeouts happened after one or two successful Batect runs (`run_as_current_user` enabled).
* If **gRPC FUSE** is _enabled_, no errors running Batect 5 times (`run_as_current_user` enabled).

**Comment by charleskorn** [comment]
Thanks for the information @mjstrasser. The Docker API call that is timing out is already set to use a 30s timeout which _should_ be plenty, but I can increase that. 

Out of interest, does running `docker run` with `docker run -u $(id -u):$(id -g) ...` produce a similar performance penalty? That is the only significant change I can think of that `run_as_current_user` introduces that could possibly cause this issue.

**Comment by charleskorn** [comment]
I've just released [0.68.1](https://github.com/batect/batect/releases/tag/0.68.1) with an increased timeout - please give it a go and let me know if it at least resolves the timeouts. (It won't make anything faster, but at least it won't fail all the time.)

**Comment by mjstrasser** [comment]
No improvement with version 0.68.1. Of 5 runs 2 succeeded then 3 failed: **gRPC FUSE** not enabled.

# Batect logs

This screenshot shows only warning and error log messages from Batect after import into a locally running Seq instance (using the [import-logs-to-seq.sh](https://github.com/mjstrasser/wiremock-async/blob/main/import-logs-to-seq.sh) script):

<img width="924" alt="image" src="https://user-images.githubusercontent.com/168173/109642517-d09e0c00-7b9e-11eb-9846-ec2648a1b8c4.png">

The same logs are extracted using:
```shell
cat batect.log | jq -c 'select(.["@severity"] == "warning" or .["@severity"] == "error")'
```
and attached: [batect-warning-error-logs.gz](https://github.com/batect/batect/files/6068295/batect-warning-error-logs.gz)

I don’t know if the extra log messages are relevant but they might be helpful.

**Comment by mjstrasser** [comment]
Running Docker directly with `-u` was interesting:

- First set of five: all succeeded without timing out.
- Second set of five: one succeeded, then the second run blocked with no messages. Restarting Docker broke the block.
- Third set of five: one succeeded, then the second run blocked in the same way.

Command is:
```shell
for ((i = 0; i < 5; i++)); do time (docker run --rm -it -u $(id -u):$(id -g) -v $HOME/dev/kotlin/wiremock-async:/code:cached -v $HOME/.gradle:/.gradle:cached -v $HOME/.m2:/.m2:cached adoptopenjdk:11-jdk-hotspot /bin/sh -c 'cd /code; /code/gradlew --no-daemon clean build'; ); done
```

**Comment by charleskorn** [comment]
That result suggests to me that there's a bug in Docker for Mac when all of the following are true:

* gRPC FUSE is disabled
* the volume is mounted with `:cached`
* a non-default user is used with `docker run` (eg. `docker run -u $(id -u):$(id -g)`)

Unfortunately there's not much I can do to fix this for you - I'd suggest raising an issue with the Docker team (in the [`docker/for-mac` repo](https://github.com/docker/for-mac/issues)) and see if they can resolve it.

**Comment by mjstrasser** [comment]
Thanks @charleskorn. I realise there is not much you can do.

I have tried to create repeatable examples with `docker run` and non-default user but outcomes are inconsistent. I will report it anyway.
