### ISSUE TITLE
Question: Common container definitions and local volume relative paths

### ISSUE THREAD

**Issue by dan-neumegen-xero** [batect/batect#829]
I'm having a problem with using central definitions for containers shared by multiple projects.

Say I have a container specified in a common batect file (lets call it batect_1.yml) in directory1, which is included in another file (batect_2.yml) in directory2.

The container definition has a volume like so:
```
volumes:
   - local: .
    container: /code
```
In the docs for [volume ](https://batect.dev/docs/reference/config/containers#volumes) it states 

> Relative paths will be resolved relative to the current configuration file's directory

When I run a task against batect_2.yml using that container, I would expect `.` to resolve to directory2, but it seems to be using the included files location, and resolving to directory1.

Is this a bug or am I misunderstanding the docs? It does limit the ability to centralise and reuse container definitions

**Comment by charleskorn** [comment]
Hey @dan-neumegen-xero, maybe I need to make the docs a bit clearer here: paths in a file are resolved relative to the directory containing the file.

So if `container-1` is defined in `/my-project/includes/container.yml`, and `/my-project/includes/container.yml` is included into `/my-project/src/batect.yml`, paths for volume mounts on `container-1` are resolved relative to `/my-project/includes`. 

If you'd like to resolve the path relative to `/my-project/src`, you can use [the `batect.project_directory` config variable](https://batect.dev/docs/reference/config/config-variables/#batectproject_directory) to get the directory containing the root configuration file.

Is that not what's happening? If so, this sounds like a bug.

**Comment by dan-neumegen-xero** [comment]
That is the exact piece of the puzzle I had missed! Thanks @charleskorn and no bugs, all working as expected
