### ISSUE TITLE
Support Fedora/Podman runtime?

### ISSUE THREAD

**Issue by fwilhe2** [batect/batect#895]
Hi,

I've tried to use batect on my fedora 34 laptop which has [podman](https://podman.io/)  installed (with the "docker" cli compatibility layer) but it seems not to be supported.

I get a `Docker is not installed, not running or not compatible with Batect: Cannot connect to '/var/run/docker.sock': Permission denied` message. True, Docker is not installed, but it would be nice if podman would be supported as it is the default container runtime on redhat-derived distros.

Is the socket really required? CLI compatibility between podman and docker seems quite good to me. I'm not sure about http api compatibility. 

Steps to reproduce:

- On Fedora 34 with `podman` and `podman-docker` installed, try running the readme example

Additional info:

- OS: Fedora 34 (Workstation Edition)
- `"dockerVersionInfo": "(Could not get Docker version information because IOException was thrown: Cannot connect to '/var/run/docker.sock': Permission denied)"`
- `    "exception": "java.io.IOException: Cannot connect to '/var/run/docker.sock': Permission denied\n\tat batect.sockets.unix.UnixSocketFactory$createSocket$1.connect(UnixSocketFactory.kt:51)\n\tat okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)\n\tat okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)\n\tat okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)\n\tat okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)\n\tat okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)\n\tat okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)\n\tat okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)\n\tat okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat batect.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:35)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)\n\tat okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)\n\tat okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)\n\tat batect.docker.api.SystemInfoAPI.ping(SystemInfoAPI.kt:94)\n\tat batect.docker.client.SystemInfoClient.checkConnectivity(SystemInfoClient.kt:65)\n\tat batect.cli.commands.DockerConnectivity.checkAndRun(DockerConnectivity.kt:40)\n\tat batect.cli.commands.RunTaskCommand.run(RunTaskCommand.kt:40)\n\tat batect.Application.runCommand(Application.kt:110)\n\tat batect.Application.run(Application.kt:82)\n\tat batect.Application.run(Application.kt:71)\n\tat batect.ApplicationKt.main(Application.kt:46)\nCaused by: java.io.IOException: Permission denied\n\tat jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:130)\n\tat jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:139)\n\tat jnr.unixsocket.UnixSocket.connect(UnixSocket.java:91)\n\tat batect.sockets.unix.UnixSocketFactory$createSocket$1.connect(UnixSocketFactory.kt:48)\n\t... 27 more\n"`

**Comment by charleskorn** [comment]
Hi @fwilhe2, I'm not familiar with Podman, so I can't answer that question specifically. 

The Docker socket or something speaking the Docker API is required, as the CLI doesn't expose all the information Batect needs for some situations in a workable format (eg. being able to get the download progress of an image pull). 

If Podman supports the Docker API, then Batect should be able to use it, but Podman specifically is not something that is supported at the moment.

**Comment by fwilhe2** [comment]
It looks like podman has a similar api, cf [Chapter 14. Using the container-tools API](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/using-the-container-tools-api_using-the-container-tools-cli), [Provides an API for the Libpod library](https://docs.podman.io/en/latest/_static/api.html).

I did not work with the docker api before, and I have not had the time to look into batect code, but do you think this could work? My hope would be that the api is compatible, so that supporting it would probably not too much effort.

**Comment by charleskorn** [comment]
It _looks_ like it would work, based on a very quick glance through the API. You'd need to set up that API to be available on your machine, either as a Unix socket at `/var/run/docker.sock` or a TCP socket.

However, reading the error message you originally posted, it looks like the `/var/run/docker.sock` socket is there, but your user doesn't have access. Perhaps you just need to give your user permission to use that socket?

**Comment by fwilhe2** [comment]
You're right, the file exists and it is a link to `/run/podman/podman.sock`. This seems to be leftover from my experiments.

Just for the sake of trying it out, when running as root I get this:

`Docker is not installed, not running or not compatible with Batect: Docker daemon responded with unknown Builder-Version ''.`

I have not checked what exactly it is looking for there, but I guess it should be fixable. Of course the question then is how much beyond that is compatible. I can't promise anything, but if I find some time to dig into the code, I'd be curious to investigate that.

For reference, the relevant log seems to be:

```
{
    "@timestamp": "2021-05-25T17:10:53.864869Z",
    "@message": "Application started.",
    "@severity": "info",
    "@source": "batect.logging.ApplicationInfoLogger",
    "@processId": 9078,
    "@threadId": 1,
    "@threadName": "main",
    "systemInfo": {
        "operatingSystem": "Linux",
        "osName": "Linux",
        "osVersion": "5.12.5-300.fc34.x86_64",
        "osArchitecture": "amd64",
        "osDetails": "Fedora 34 (Workstation Edition) (fedora)",
        "lineSeparator": "\n",
        "jvmVersion": "Red Hat, Inc. OpenJDK 64-Bit Server VM 11.0.11",
        "userName": "root",
        "homeDirectory": "/root",
        "tempDirectory": "/tmp"
    },
    "gitVersion": "2.31.1",
    "environment": {
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin",
        "XAUTHORITY": "/run/user/1000/.mutter-Xwaylandauth.U6OU30",
        "SHELL": "/bin/bash",
        "HISTSIZE": "50000",
        "TERM": "xterm-256color",
        "USER": "root",
        "LANG": "en_US.UTF-8",
        "BATECT_WRAPPER_DID_DOWNLOAD": "false",
        "SUDO_USER": "florian",
        "SUDO_COMMAND": "./batect --log-file=bar shell",
        "BATECT_WRAPPER_SCRIPT_DIR": "/home/florian/code/system-automation",
        "DISPLAY": ":0",
        "SUDO_GID": "1000",
        "MAIL": "/var/spool/mail/florian",
        "HOSTNAME": "fedora",
        "COLORTERM": "truecolor",
        "USERNAME": "florian",
        "LOGNAME": "root",
        "SUDO_UID": "1000",
        "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:",
        "PWD": "/home/florian/code/system-automation",
        "BATECT_WRAPPER_CACHE_DIR": "/root/.batect/cache",
        "SHLVL": "0",
        "HOME": "/root"
    },
    "versionInfo": {
        "gitCommitHash": "7d12db96f5e8dd7f9dedae325ad79081871c4909",
        "gitCommitDate": "2021-05-05 09:15:06 +1000",
        "version": "0.70.1",
        "buildDate": "2021-05-04 23:31:03 +0000"
    },
    "commandLine": [
        "--log-file=bar",
        "shell"
    ],
    "consoleInfo": {
        "stdinIsTTY": true,
        "stdoutIsTTY": true,
        "supportsInteractivity": true,
        "terminalType": "xterm-256color"
    },
    "dockerVersionInfo": "3.1.2 (API version: 1.40, minimum supported API version: 1.24, commit: , operating system: 'linux', experimental: true)"
}

{
    "@timestamp": "2021-05-25T17:10:53.990058Z",
    "@message": "Connectivity check failed.",
    "@severity": "warning",
    "@source": "batect.docker.client.SystemInfoClient",
    "@processId": 9078,
    "@threadId": 1,
    "@threadName": "main",
    "exception": "batect.docker.DockerException: Docker daemon responded with unknown Builder-Version ''.\n\tat batect.docker.api.SystemInfoAPI.ping(SystemInfoAPI.kt:115)\n\tat batect.docker.client.SystemInfoClient.checkConnectivity(SystemInfoClient.kt:65)\n\tat batect.cli.commands.DockerConnectivity.checkAndRun(DockerConnectivity.kt:40)\n\tat batect.cli.commands.RunTaskCommand.run(RunTaskCommand.kt:40)\n\tat batect.Application.runCommand(Application.kt:110)\n\tat batect.Application.run(Application.kt:82)\n\tat batect.Application.run(Application.kt:71)\n\tat batect.ApplicationKt.main(Application.kt:46)\n"
}
```

**Comment by charleskorn** [comment]
OK, that's progress. If you are interested in submitting a PR to fix this, [this](https://github.com/batect/batect/blob/a1c3e9bf9ccae4019c0434f93b74847b01c3677e/libs/docker-client/src/main/kotlin/batect/docker/api/SystemInfoAPI.kt#L112) is the likely area of the code you'd need to change.

**Comment by charleskorn** [comment]
I've just pushed a fix for this issue, and it will be included in the next release. Please feel free to open another issue if you run into further problems.
