### ISSUE TITLE
Ask user to confirm command and run it after making correction suggestion

### ISSUE THREAD

**Issue by jobasiimwe** [batect/batect#92]
As a user,
When I mis-type the task name
And...batect gives you a suggestion of what I mostlikely meant,
I want batect to ask me to confirm if that is the command i meant (probably with y/n) and if i confirm...i want batect to run that command

**Comment by charleskorn** [comment]
Nice idea, thanks @jobasiimwe.

**Comment by charleskorn** [comment]
I'm going to close this as won't fix - with the introduction of [shell tab completion](https://batect.dev/docs/getting-started/shell-tab-completion/), I believe there's less of a need for this. If you disagree, please feel free to reopen this issue.
