### ISSUE TITLE
Is using host network possible in Batect?

### ISSUE THREAD

**Issue by Mubashwer** [batect/batect#930]
Is it possible to use host network in Batect?

Fore more information: https://docs.docker.com/network/host/

**Comment by charleskorn** [comment]
Hi @Mubashwer, this is currently not supported. Could you tell me a little more about why you'd like to use host networking?

**Comment by Mubashwer** [comment]
@charleskorn We have 3 containers. One is identity, one is our spa and one is a cypress container. We were having intermittent `ECONNREFUSED` error from cypress randomly in some of the tests where cypress failed to connect to the spa (which depends on identity). The dependencies were correctly set so they should be using the same network. The issue doesn't happen when we run containers with host network via docker compose.

The issue is entirely random and intermittent.

**Comment by charleskorn** [comment]
Do you have [a health check](https://batect.dev/docs/how-to/wait-for-dependencies) defined for your SPA? It may be that Cypress is starting too quickly and trying to start using the application before it is ready.

**Comment by Mubashwer** [comment]
We do have a healthcheck and the cypress tests start after the spa is up. The intermittent ECONNREFUSE happens in the middle of the tests. (i.e not necessarily the first spec file).

**Comment by charleskorn** [comment]
OK, weird. Do you see the same issue with Docker Compose when not using host networking?

**Comment by Mubashwer** [comment]
> OK, weird. Do you see the same issue with Docker Compose when not using host networking?

Did not try that.

**Comment by charleskorn** [comment]
I know this is going off topic from your original question, but would you mind giving that (Docker Compose without host networking) a go? 

I'm hesitant to add host networking support to Batect as it would break one of the core ideas of Batect, that each task runs in its own isolated network, so if this is an issue with how Batect is setting up the isolated network, I'd be keen to fix that.

**Comment by Mubashwer** [comment]
> I'm hesitant to add host networking support to Batect as it would break one of the core ideas of Batect, that each task runs in its own isolated network

In batect, you can pass a docker network:
```
docker network create -d bridge my-network
./batect --use-network=my-network my-task
```

In the above case, the docker network is not necessarily isolated as there is no restrictions on how the network is used.

So I was thinking maybe we could do something like:
```
./batect --use-network=host my-task
```

(docker network with name 'host' cannot be created so the above syntax is suitable)

> but would you mind giving that (Docker Compose without host networking) a go?

Ok. I will give that a shot when I find the time and will let you know. It is a bizarre issue, indeed.

**Comment by kllp** [comment]
I run a docker compose based setup on localhost that I want to test with batect. 
I found 
```
extra_hosts:
      - "host.docker.internal:host-gateway"
```
but I think it doesn't translate to batect.

How can I use localhost inside a test container so it refers to the host?

**Comment by charleskorn** [comment]
@klip, have you tried using the hostname `host.docker.internal`? That _should_ work. 

If not, extra hosts are supported just like you've given there - is that not working for you?

**Comment by kllp** [comment]
Thank you for your answer!
In batect.yml
```
    additional_hosts:
      host.docker.internal: host-gateway
```
works.
I couldn't get `localhost: host-gateway` to work but that's a docker or linux issue with `/etc/hosts`
