### ISSUE TITLE
Batect 0.70.0 not reading DOCKER_CERT_PATH environment variable

### ISSUE THREAD

**Issue by Tzrlk** [batect/batect#935]
I've got a CI build running that sets the DOCKER_CERT_PATH env var, but batect doesn't pick it up for some reason:
```
$ env | grep DOCKER | sort
DOCKER_BUILDKIT=1
DOCKER_CERT_PATH=/certs/client
DOCKER_HOST=tcp://localhost:2376
DOCKER_PASS=[MASKED]
DOCKER_REGISTRY=docker.bravurasolutions.net:6555
DOCKER_TLS_CERTDIR=/certs
DOCKER_TLS_VERIFY=1
DOCKER_USER=automatedbuild_int
FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR=false
FF_SKIP_DOCKER_MACHINE_PROVISION_ON_CREATION_FAILURE=false
$ ./batect --skip-prerequisites golang:deps
Downloading Batect version 0.70.0 from https://updates.batect.dev/v1/files/0.70.0/batect-0.70.0.jar...
##O=#  #                                                                      
######################################################################## 100.0%
##########################                                                37.0%
#############################################################             85.9%
######################################################################## 100.0%
java.nio.file.NoSuchFileException: /root/.docker/key.pem
```
Specifying the property as --docker-cert-path in the command works fine:
```
$ ./batect --docker-cert-path=/certs/client --skip-prerequisites terraform:init
Downloading Batect version 0.70.0 from https://updates.batect.dev/v1/files/0.70.0/batect-0.70.0.jar...
##O#-#                                                                        
######################################################################## 100.0%
Running terraform:init...
Building workspace...
Built workspace.
Running sh -c " source /etc/.ashrc && terraform ${*} init -backend=false " -- in workspace...
```

**Comment by Tzrlk** [comment]
I was kinda hoping that I'd just find a typo in the code, but the CommandLineOptionsParser looks fine:
```kotlin
    private val dockerCertificateDirectoryOption = valueOption(
        dockerConnectionOptionsGroup,
        "docker-cert-path",
        "Path to directory containing certificates to use to provide authentication to the Docker host and authenticate the Docker host. Has no effect if ${dockerUseTLSOption.longOption} is not set, and takes precedence over ${dockerConfigDirectoryOption.longOption}.",
        environmentVariableDefaultValueProviderFactory.create("DOCKER_CERT_PATH", defaultDockerConfigDirectory, ValueConverters.pathToDirectory(pathResolverFactory, mustExist = true)),
        ValueConverters.pathToDirectory(pathResolverFactory, mustExist = true)
    )
```
Manually specifying `--docker-tls` in the command makes no difference either.

**Comment by Tzrlk** [comment]
Ah, found the issue. The value for the environment variable wasn't being interpolated by the parser:
```
$ ./batect --docker-cert-path=${DOCKER_CERT_PATH} --skip-prerequisites terraform:init
Downloading Batect version 0.70.0 from https://updates.batect.dev/v1/files/0.70.0/batect-0.70.0.jar...
#=#=#                                                                         
######################################################################## 100.0%
######################                                                    31.8%
####################################################                      73.6%
######################################################################## 100.0%
The value '${DOCKER_TLS_CERTDIR}/client' for option '--docker-cert-path=${DOCKER_TLS_CERTDIR}/client' is invalid: The directory '${DOCKER_TLS_CERTDIR}/client' (resolved to '/builds/X_NZpcW2/1/<redacted>/${DOCKER_TLS_CERTDIR}/client') does not exist.
```

**Comment by Tzrlk** [comment]
Tell a lie, setting the environment variable specifically to `/certs/client` actually just ignored it again. FYI, `/certs` is a volume mount needed for docker-in-docker.

**Comment by charleskorn** [comment]
Thanks for the detailed report @Tzrlk. Does it work as expected if you provide the path to the certificate files on the command line? Something like `./batect --docker-tls-ca-cert=${DOCKER_CERT_PATH}/ca.pem --docker-tls-cert=${DOCKER_CERT_PATH}/cert.pem --docker-tls-key=${DOCKER_CERT_PATH}/key.pem terraform:init`

**Comment by Tzrlk** [comment]
Nope:
```
The value '${DOCKER_TLS_CERTDIR}/client/ca.pem' for option '--docker-tls-ca-cert=${DOCKER_TLS_CERTDIR}/client/ca.pem' is invalid: The file '${DOCKER_TLS_CERTDIR}/client/ca.pem' (resolved to '/builds/X_NZpcW2/1/<redacted>/${DOCKER_TLS_CERTDIR}/client/ca.pem') does not exist.
```
Though it will work if the `${DOCKER_CERT_PATH}` is set to `/certs/client` instead of `${DOCKER_TLS_CERTDIR}/client`. Not actually sure if this is specifically a batect issue, but if the code performing parameter evaluation could be enhanced to take nested interpolation into account, it would make things a little less awkward.

Java/Kotlin doesn't really have an idiomatic way of doing this, but I found this solution on StackOverflow that doesn't seem too offensive: https://stackoverflow.com/a/58772236/41223

**Comment by charleskorn** [comment]
I suspect your suspicion that this isn't a Batect issue is correct: interpolation of environment variables into command lines should be taken care of by your shell, not Batect. 

So if you're seeing an error message like `The value '${DOCKER_TLS_CERTDIR}/client/ca.pem' for option '--docker-tls-ca-cert=${DOCKER_TLS_CERTDIR}/client/ca.pem' is invalid...`, that suggests that whatever is invoking Batect is not substituting environment variables correctly. Batect is being passed the a literal string with `${DOCKER_TLS_CERTDIR}/client/ca.pem` in it, instead of `/certs/client/ca.pem`.

How are you invoking Batect? Are you running this yourself using Bash or another shell, or invoking it using another tool?

**Comment by Tzrlk** [comment]
I'm trying to get batect running in a kubernetes-based Gitlab runner, and it's a nightmare. I'd contribute docs on how to get it running if I ever actually do. Finally got docker-in-docker acting as the host, only to find that the run-as-user feature causes permissions errors, but turning it off also causes permissions errors. Extremely frustrating.

**Comment by charleskorn** [comment]
> Finally got docker-in-docker acting as the host, only to find that the run-as-user feature causes permissions errors, but turning it off also causes permissions errors.

Are you able to share the error messages you're seeing? I might be able to help out.

I've also found the source of your original issue (setting the `DOCKER_CERT_PATH` environment variable did nothing) - I'm working on a fix and will release it when I have some time.

**Comment by charleskorn** [comment]
I've fixed the issue where setting `DOCKER_CERT_PATH` didn't behave as expected and will release a new version shortly. 

If you'd like help getting Batect working within a Kubernetes-based GitLab runner, please feel free to open another issue or start a discussion thread, I'd be glad to help where I can.
