### ISSUE TITLE
Support specify build stage in Dockerfile

### ISSUE THREAD

**Issue by diwang-xero** [batect/batect#938]
In a multi stage Dockerfile, we can specify which target we can stop when building the image, doc [Stop at a specific build stage](https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage).
In docker-compose.yml, we can also do [that](https://docs.docker.com/compose/compose-file/compose-file-v3/#target).
Can we also add this support in batect, so we can reuse the same Dockerfile for different usages? Thanks!

**Comment by charleskorn** [comment]
Hey @diwang-xero, thanks for the suggestion. This should be straightforward to implement, I'll add it to my backlog. In the meantime, if you're interested in making a PR, I'm always open to that as well :)

**Comment by charleskorn** [comment]
I've just added support for this and it will be included in the next release. Thanks again for the suggestion @diwang-xero!
