### ISSUE TITLE
Batect task failed with `stdin is not a tty`

### ISSUE THREAD

**Issue by mario-prabowo-xero** [batect/batect#945]
**Issue:** Batect task failed with error message `stdin is not a tty`. 
- This only happens when executing batect task from git pre-push script and not when running the task directly
- The issue also doesn't happen when running the pre-push script manually and only happens when doing git push
- The issue looks similar to issues found in [Yarn](https://github.com/yarnpkg/yarn/issues/2998)/[Husky](https://github.com/typicode/husky/issues/627). The workaround suggested in https://github.com/typicode/husky/issues/627 works but it requires us to copy paste the command everywhere and we are not sure how it will affect other team members using Mac

**Batect Version:** from v 0.66.1 onwards (our team member reported that it was working fine in v 0.62 before migrating to v 0.66.1)
**Operating System:** Windows 10.

**Comment by charleskorn** [comment]
Hi @mario-prabowo-xero, thanks for the bug report. Just to confirm, are you using the most recent version of Batect? 

If you are, are you able to share a sample project that demonstrates the issue?

**Comment by mario-prabowo-xero** [comment]
Hi @charleskorn,

Thanks for your prompt response. We are using the latest version (0.72.0). We can't share the code as it's commercially sensitive, but I can try creating a sample project to reproduce the issue.

Thanks,

Mario

**Comment by mario-prabowo-xero** [comment]
Hi @charleskorn,

I managed to reproduce the issue in my sample project. You can find it in https://github.com/mario-prabowo-xero/sample-batect.

Thanks,

Mario

**Comment by charleskorn** [comment]
Thanks for the reproduction repo @mario-prabowo-xero. I've been able to fix the issue and it will be included in the next release.

For the time being, you can make this change to line 86 of the `batect` wrapper script in your project to fix the problem:

```diff
-        if [[ "$(uname -o 2>&1)" == "Msys" ]] && hash winpty 2>/dev/null; then
+        if [[ "$(uname -o 2>&1)" == "Msys" ]] && hash winpty 2>/dev/null && [ -t /dev/stdin ]; then
```

**Comment by mario-prabowo-xero** [comment]
Fantastic! Thanks for fixing it so quickly @charleskorn.
