### ISSUE TITLE
Cache initialisation fails on Ubuntu 20.04 on Raspberry PI

### ISSUE THREAD

**Issue by gabrielsadaka** [batect/batect#947]
When trying to run batect on a Raspberry PI running Ubuntu 20.04 using a cache volume I get the following error:

```
Running run...
build-env: waiting for cache initialisation to finish...

Error: Could not initialise caches for task.
Running the cache initialisation container failed: the container exited with exit code 1 and output:
standard_init_linux.go:228: exec user process caused: exec format error


Clean up: done

The task run failed. See above for details.
```

It works fine when I remove `type: cache` though. It also works fine with Ubuntu 16.04 running via WSL2 on Windows, on Windows itself and on MacOS. 

Here's a repro: https://github.com/gabrielsadaka/batect-cache-issue-repro

My guess is it is due to the RPI having an ARM based CPU but I don't have Ubuntu running on an x86 CPU to test that theory.

**Comment by charleskorn** [comment]
Thanks for the bug report @gabrielsadaka. You're right, this would be an issue with running on a non-x86 CPU. I'll take a look at providing an ARM64 version with the image as well.

**Comment by gabrielsadaka** [comment]
That would be great, thanks @charleskorn. 

Does batect make use of native assemblies as well as a Java app?

**Comment by charleskorn** [comment]
>Does batect make use of native assemblies as well as a Java app?

It does make some calls to non-Java functions from Java, but they _should_ work fine on ARM. Are you running into issues that might be caused by that?

**Comment by gabrielsadaka** [comment]
Not that I know of, the only issue I have run into is the cache volume type error.

I was just wondering what you would need to produce an AMR64 version of, as you suggested could be included in the image.

**Comment by charleskorn** [comment]
Ah sorry, I misunderstood - the cache init image contains a separate, statically compiled Golang app that needs to built for each architecture.

**Comment by gabrielsadaka** [comment]
Ah makes sense. I didn't know the cache initialisation happened by a separate docker image, I just assumed batect did that using docker API calls.

**Comment by charleskorn** [comment]
I've just pushed a fix for this and it will be included in the next release. 

In the meantime, you can pass the `--linux-cache-init-image=batect/batect-cache-init-image@sha256:eb29737360eede3543065a4ebfa853043a91631260ce2f4aa1d0cb4d0943a431` option on the command line, or set the `BATECT_LINUX_CACHE_INIT_IMAGE` environment variable to `batect/batect-cache-init-image@sha256:eb29737360eede3543065a4ebfa853043a91631260ce2f4aa1d0cb4d0943a431`.

**Comment by charleskorn** [comment]
>Ah makes sense. I didn't know the cache initialisation happened by a separate docker image, I just assumed batect did that using docker API calls.

Sadly not... in order to support 'run as current user' mode, we have to use another image to set the owner of the volume before it's used as a cache by other containers.

**Comment by gabrielsadaka** [comment]
The environment variable worked perfectly, thanks! 

> Sadly not... in order to support 'run as current user' mode, we have to use another image to set the owner of the volume before it's used as a cache by other containers.

Fair enough, that's unfortunate but good to know.
