### ISSUE TITLE
Migrate remaining Groovy Gradle scripts to Kotlin

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#981]
### Describe the problem you'd like to solve

There currently is an inconsistent mix of Groovy and Kotlin Gradle build files.

### Describe the solution you'd like

Migrate all build files to Kotlin script, to align with other scripts and the main application code.

### Additional context

I can help with this if desired.

**Comment by charleskorn** [comment]
If you're interested in submitting PRs for this, I'd be very grateful - this has been on my to-do list for a while but it's never the most important thing to do.

**Comment by sschuberth** [comment]
Let's start slowly: https://github.com/batect/batect/pull/985

**Comment by sschuberth** [comment]
FYI, I'm working on migrating the *wrapper* module script, but ran into [this issue](https://youtrack.jetbrains.com/issue/KTIJ-19341#focus=Comments-27-5151860.0-0) which blocks me for now. I have some hope that https://github.com/batect/batect/pull/976 might do something good about it.

**Comment by charleskorn** [comment]
Awesome, thanks. #976 won't be merged until there's a fix out for [this issue](https://youtrack.jetbrains.com/issue/KT-48295), which [breaks our tests](https://github.com/batect/batect/pull/976/checks?check_run_id=3439105774#step:5:7534).

**Comment by sschuberth** [comment]
> FYI, I'm working on migrating the _wrapper_ module scripts, but ran into [this issue](https://youtrack.jetbrains.com/issue/KTIJ-19341#focus=Comments-27-5151860.0-0) which blocks me for now.

Turns out I can resolve this by aligning the configured Project SDK and Gradle JVM in IntelliJ as [indicated here](https://youtrack.jetbrains.com/issue/KTIJ-1277#focus=Comments-27-4706475.0-0). So I'll continue to work on the migration.

**Comment by sschuberth** [comment]
I'll continue working on this at some point.

**Comment by charleskorn** [comment]
No worries at all, there's no rush and I appreciate what you've already done!

**Comment by sschuberth** [comment]
@charleskorn, looks like the current code base contains no more Groovy-related code, so I guess this is done and can be closed?

**Comment by sschuberth** [comment]
Ah, no, there's still these:

- app/gradle/journeyTest.gradle
- app/gradle/shadow.gradle
- app/gradle/versionInfo.gradle
- gradle/utilities.gradle
- gradle/versioning.gradle

**Comment by charleskorn** [comment]
> I'll give it a try to finish migrating these.

That would be great, thanks for your help @sschuberth!
