### ISSUE TITLE
Add examples on how to cache ~/.gradle for Gradle projects

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#982]
### Describe the problem you'd like to solve

The docs contains example on [how to cache](https://batect.dev/docs/how-to/performance#cache-volumes) `node_modules` for NPM projects. However, these examples to do straight apply to e.g. Gradle (or Maven) builds which cache dependencies outside of the code working tree, under the user home.

### Describe the solution you'd like

Document more examples for dependency caching for more build systems than NPM, preferably Gradle and Maven.

### Describe alternatives you've considered

Alternatively (or additionally), it would be cool to dog-feed *batect*, and have a `batect.yml` for batect itself, which would be an example for a Gradle project.

**Comment by sschuberth** [comment]
Sorry, for overlooking that section somehow, that indeed comes close. However, it seems to be quite outdated. The linked Gradle issue as been closed since Gradle 6.2, and by then there's the possibility to use a [shareable, read-only dependency cache](https://github.com/gradle/gradle/issues/851#issuecomment-581407924) which seems to be a good fit for *Batect* use.

I'll experiment a bit an eventually contribute some docs improvements that make the section read more like a "Batect best practices for Gradle projects" (in terms of build performance) than "just" examples.

**Comment by charleskorn** [comment]
Any improvements or suggestions would be great. The docs are maintained in a separate repo, for example, that page is: https://github.com/batect/batect.dev/blob/main/docs/using-batect-with/tools/gradle.md
