### ISSUE TITLE
Generated embedded PoweShell script contains duplicate line endings

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#993]
### Describe the bug

When embedding the Powershell script into `batect.cmd`, original line endings get dublicated, resulting in alternating blank lines in `batect.cmd`, which seems unnecessary:

https://github.com/batect/batect/blob/f936697c0ff947ea60b85fadf6343d66bdc84457/wrapper/windows/build.gradle#L58-L59

### Steps to reproduce

Take a look at e.g. https://github.com/batect/batect/releases/download/0.73.0/batect.cmd.

### Expected behaviour

I would expected to see no blank lines between original lines, but only the `^`-escaping.

### Actual behaviour

Lines are split, and then merged again with duplicate line endings.

### Version information

```plain text
Version 0.73.0.
```

### Any other information

It *might* be that these additional blank lines are in fact required in order to embed `.ps1` into `.cmd` code, but if so, that should at least be documented in the code, IMO.

**Comment by charleskorn** [comment]
> It might be that these additional blank lines are in fact required in order to embed .ps1 into .cmd code, but if so, that should at least be documented in the code, IMO.

Yep, this is expected and yep, it should be documented. A `^` without a following blank line would only add a space to the result, rather than a new line character.
