### ISSUE TITLE
Consider using clikt for command line parsing

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#994]
### Describe the problem you'd like to solve

Batect currently seems to implement its own command line parsing. In order to focus on Batect's core functionality, it might make sense to use a (multi-platform) third-party library instead.

### Describe the solution you'd like

I propose to use https://github.com/ajalt/clikt, which I also use at https://github.com/oss-review-toolkit/ort/tree/master/cli and personally made good experience with.

**Comment by charleskorn** [comment]
Thanks for the suggestion @sschuberth. At the time I started writing Batect, frameworks like clikt either didn't exist or were very immature, but it's worth relooking at this to see if it's worth switching to a library.

**Comment by sschuberth** [comment]
> but it's worth relooking at this to see if it's worth switching to a library.

Should this "relooking" be performed by you @charleskorn, or can the community just come up with a PR that implements a switch?

**Comment by sschuberth** [comment]
BTW, I also find the [Why not X?](https://ajalt.github.io/clikt/whyclikt/) sections in *clikt*'s docs to be a good read.

**Comment by charleskorn** [comment]
> > but it's worth relooking at this to see if it's worth switching to a library.
> 
> Should this "relooking" be performed by you @charleskorn, or can the community just come up with a PR that implements a switch?

I'm open to suggestions or PRs from anyone, but at the moment, this isn't a high priority for me - what's currently there is working well and there are more pressing things to look at first.
