### ISSUE TITLE
Alternative backends

### ISSUE THREAD

**Issue by ineffyble** [batect/batect#998]
### Describe the problem you'd like to solve

With the recent announcement of licensing changes for Docker Desktop I suspect we will see some shifts away from Docker in favour of other container orchestration tools (Docker is perfectly capable of running without Docker Desktop but it does seem to make things trickier on non-Linux hosts).

I think it's worth noting that Kubernetes recently moved away from Docker in favour of running containerd directly. I don't know how much more low level this is, and whether it would be unrealistic for batect to talk to containerd directly in future, but could be an option.

There are several Docker-ish options out there such as Podman too, which apparently has a Docker- compatible REST API.

### Describe the solution you'd like

The ability to use batect with alternative container orchestration tools / OCI runtimes.

**Comment by charleskorn** [comment]
Great question @ineffyble. I'm going to wait and see if any specific options become particularly popular before committing to adding support for any of them, but this is definitely on my radar. 

Podman in particular seems like a likely candidate given its compatibility with Docker's API, as you mentioned. (#895 was raised previously for Podman - Batect _should_ work fine with it now, but I haven't tested it extensively myself.)

**Comment by charleskorn** [comment]
Since the announcement by Docker earlier this year, I haven't heard much noise about people moving away from Docker or Docker Desktop (but this may just be the bubble I exist in). 

Of those that I have seen talking about this, Podman seems to be the most frequently cited option. Have you seen much discussion about any other options @ineffyble?

**Comment by charleskorn** [comment]
If anyone comes across this issue looking for information on how to use Colima with Batect, @jcartledge has put together https://gist.github.com/jcartledge/0ce114e9719a62a4776569e80088511d which shows how to do exactly that.

A similar technique can be used for other alternative Docker backends that don't use the standard `/var/run/docker.sock` location for the Docker API socket.

I'm working on adding support for Docker CLI contexts to Batect so setting `DOCKER_HOST` isn't necessary, but this will be required for now.

**Comment by binkley** [comment]
I did not have success with the approach from @jcartledge.  I'm casually poking at what works for me.

**Comment by charleskorn** [comment]
> I did not have success with the approach from @jcartledge.  I'm casually poking at what works for me.

Could you expand on this a little @binkley? What's not working for you? Do you get an error message?

**Comment by charleskorn** [comment]
> I'm working on adding support for Docker CLI contexts to Batect so setting `DOCKER_HOST` isn't necessary, but this will be required for now.

And this is now available in [v0.80.0](https://github.com/batect/batect/releases/tag/0.80.0) 🎉 Setting `DOCKER_HOST` should no longer be required to use Batect with Colima. Please give the new version a go and let me know if you run into any issues.

**Comment by chadlwilson** [comment]
Thanks @charleskorn - this is much more convenient now and seems to be working great :-)
